---
permalink: rhel-install/concept_advanced_configuring_oncommand_workflow_automation.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Workflow Automation \(WFA\) enables you to configure various settings—for example, AutoSupport and notifications.'
---
= Configuring OnCommand Workflow Automation
:icons: font
:imagesdir: ../media/

OnCommand Workflow Automation (WFA) enables you to configure various settings--for example, AutoSupport and notifications.

When configuring WFA, you can set up one or more of the following, as required:

* AutoSupport (ASUP) for sending ASUP messages to technical support
* Microsoft Active Directory Lightweight Directory Access Protocol (LDAP) server for LDAP authentication and authorization for WFA users
* Mail for email notifications about workflow operations and sending ASUP messages
* Simple Network Management Protocol (SNMP) for notifications about workflow operations
* Syslog for remote data logging

*Related information*

xref:task_configuring_autosupport.adoc[Configuring AutoSupport]

xref:task_configuring_authentication_settings.adoc[Configuring authentication settings]

xref:task_configuring_mail.adoc[Configuring email notifications]

xref:task_configuring_snmp.adoc[Configuring SNMP]

xref:task_configuring_syslog.adoc[Configuring Syslog]

xref:task_accessing_oncommand_workflow_automation.adoc[Accessing OnCommand Workflow Automation]
