---
permalink: rhel-install/concept-unsupported-features-for-wfa-on-linux.html
sidebar: sidebar
keywords: oncommand workflow automation, known, limitations
summary: "OnCommand Workflow Automation (WFA) 5.0 includes some limitations and unsupported features that you should be aware of before you install and configure WFA."
---
= Known limitations for OnCommand Workflow Automation
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Workflow Automation (WFA) 5.0 includes some limitations and unsupported features that you should be aware of before you install and configure WFA.

*LDAP authentication*

 * You can use only Microsoft Active Directory Lightweight Directory Access Protocol (LDAP) server for LDAP authentication.
 * You must not use an LDAP user name that is part of a hierarchical structure of multiple domains for authentication or notification.

[NOTE]
====
Microsoft Active Directory Lightweight Directory Services (AD LDS) is not supported.
====
*WFA data sources types*

Active IQ Data Center Manager 6.0, 6.1, and 6.2 data source types are deprecated in the WFA 4.1 release, and these data source types will not be supported in future releases.

*WFA installed on Linux*

 * Certified content from Data ONTAP operating in 7-Mode is currently not available.
 * Commands that include only PowerShell code are not compatible with Linux.
 * Certified commands for 7-Mode and VMware are currently not ported to Perl, and are therefore not compatible with Linux.
