---
permalink: rhel-install/reference_system_requirements_for_oncommand_workflow_automation_linux.html
sidebar: sidebar
keywords: OnCommand Workflow Automation
summary: 'You must be aware of the OnCommand Workflow Automation \(WFA\) hardware and software requirements before installing WFA.'
---
= System requirements for installing OnCommand Workflow Automation
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of the OnCommand Workflow Automation (WFA) hardware and software requirements before installing WFA.

== Hardware requirements for installing WFA

The following table lists the minimum hardware requirements and the recommended hardware specifications for the WFA server.

|===
| Component| Minimum requirements| Recommended specifications
a|
CPU
a|
2.27 GHz or faster, 2 core, 64-bit
a|
2.27 GHz or faster, 2 core, 64-bit
a|
RAM
a|
4 GB
a|
8 GB
a|
Free disk space
a|
5 GB
a|
20 GB
|===
*Note:* If you are installing WFA on a virtual machine (VM), you should reserve the required memory and CPU so that the VM has sufficient resources. The installer does not verify the CPU speed.

== Software requirements for installing WFA

The following table lists all the operating system versions compatible with the WFA server.

|===
a|
Operating System
a|
Version
a|
Red Hat Enterprise Linux
a|
6.5, 7.0, 7.1 64-bit operating systems, 7.2, 7.3 and 7.4
a|
CentOS
a|
7.1, 7.2, and 7.3
|===
*Note:* WFA should be installed on dedicated physical machines or VMs. You must not install any other application on the server that runs WFA.

* One of the following supported browsers:
 ** Mozilla Firefox
 ** Microsoft Internet Explorer
 ** Google Chrome
* The latest version of Adobe Flash Player for your browser
* Perl v5.10.1
+
You can obtain information about the Perl modules that should be installed by using the `./WFA-version_number.bin -l` command.

For more details, see the https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool].

*Related information*

xref:reference_ports_required_for_oncommand_workflow_automation.adoc[Ports required for Workflow Automation]

http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
