---
permalink: rhel-install/task_migrate_the_oncommand_workflow_automation_installation_linux.html
sidebar: sidebar
keywords: migrate, oncommand workflow automation, installation
summary: "You can migrate an OnCommand Workflow Automation (WFA) installation to maintain the unique WFA database key that is installed during the WFA installation."
---
= Migrate the OnCommand Workflow Automation installation
:icons: font
:imagesdir: ../media/

[.lead]
You can migrate an OnCommand Workflow Automation (WFA) installation to maintain the unique WFA database key that is installed during the WFA installation.

*About this task*

* You must perform this procedure only when you want to migrate a WFA installation that includes the WFA database key to a different server.
* A WFA database restore does not migrate the WFA key.
* Migrating a WFA installation does not migrate the SSL certificates.
* The default WFA installation path is used in this procedure.
+
If you changed the default location during installation, you must use the changed WFA installation path.

.Steps
. Access WFA through a web browser as an admin.
. Back up the WFA database.
. Open a shell prompt on the WFA server and change directories to the following location:
+
`WFA_install_location/wfa/bin/`
. Enter the following at the shell prompt to obtain the database key: `./wfa -key`
. Note the database key that is displayed.
. Uninstall WFA.
. Install WFA on the required system.
. Open a shell prompt on the WFA server and change the directories to the following location:
+
`WFA_install_location/wfa/bin/`
. At the shell prompt, install the database key by entering the following command:
+
`./wfa -key=yourdatabasekey`
+
`yourdatabasekey` is the key that you noted from the previous WFA installation.

. Restore the WFA database from the backup that you created.
