---
permalink: rhel-install/task-restore-full-the-oncommand-workflow-automation-database-and-configurations-linux.html
sidebar: sidebar
keywords: oncommand workflow automation, restore, database, cli
summary: "You can do a full restore of the OnCommand Workflow Automation (WFA) database and supported configurations that you backed up previously by using the command-line interface (CLI). In a full restore, you can restore the WFA database, WFA configuration, and key."
---
= Restore (full) the WFA database using the CLI
:icons: font
:imagesdir: ../media/

[.lead]
You can do a full restore of the OnCommand Workflow Automation (WFA) database and supported configurations that you backed up previously by using the command-line interface (CLI). In a full restore, you can restore the WFA database, WFA configuration, and key.

.What you'll need

* You must have created a backup of the WFA database.
* You must have admin or architect credentials.

.Steps

. At the shell prompt, navigate to the following directory on the WFA server:
+
`WFA_install_location/wfa/bin`
+
`wfa_install_location` is the WFA installation directory.

. Restore the WFA database:
+
`wfa --restore --full --user=user_name [--password=password] [--location=path] --restart`

 ** _user_name_ is the user name of the admin or architect user.
 ** _password_ is the password of the user.
+
If you have not provided the password, you must enter the password when prompted.

 ** _path_ is the complete directory path to the restore file.
. Verify that the restore operation is successful and WFA is accessible.
