---
permalink: rhel-install/task_create_a_support_case_for_wfa.html
sidebar: sidebar
keywords: create, support, case, oncommand workflow automation
summary: "You can create support cases for OnCommand Workflow Automation (WFA) issues that require assistance from technical support. You must use the technical triage template for creating a support case."
---
= Create a support case for OnCommand Workflow Automation
:icons: font
:imagesdir: ../media/

[.lead]
You can create support cases for OnCommand Workflow Automation (WFA) issues that require assistance from technical support. You must use the technical triage template for creating a support case.

*About this task*

The technical triage template for WFA provides all the required information for creating a support case. You must use the questions and information in the technical triage template to construct your issue, which helps in improving the time required for the resolution of your case.

.Steps
. Access the WFA technical triage template.
+
https://kb.netapp.com/support/index?page=content&id=1013484[NetApp KB Article 1013484: Triage Template - How to Troubleshoot OnCommand Workflow Automation^]

. Use the template to construct and send your case to technical support.
