---
permalink: rhel-install/task-configure-vcs-to-install-wfa.html
sidebar: sidebar
keywords: configure, vcs, install, oncommand workflow automation
summary: "Before you install OnCommand Workflow Automation (WFA) in Veritas Cluster Server (VCS), you must ensure that the cluster nodes are properly configured to support WFA."
---
= Configure VCS to install OnCommand Workflow Automation
:icons: font
:imagesdir: ../media/

[.lead]
Before you install OnCommand Workflow Automation (WFA) in Veritas Cluster Server (VCS), you must ensure that the cluster nodes are properly configured to support WFA.

*What you'll need*

* VCS must be installed on both nodes of the cluster according to the instructions in the _Veritas Cluster Server 6.1.1 Installation Guide_.
* To receive notifications about cluster events, VCS software must be configured for SNMP and SMTP according to the instructions in the _Veritas Cluster Server Administrator's Guide_.
* All requirements and guidelines for configuring cluster servers must be met according to the VCS documentation.
* SnapDrive for UNIX must be installed if you want to create LUNs using SnapDrive for UNIX.
* Both the cluster nodes must be running a supported version of the operating system.
+
The minimum supported operating systems are Red Hat Enterprise Linux 6.5 and VCS 6.1.1.

* The same version of WFA must be installed using the same path on both the cluster nodes.
* The WFA server must be connected to the storage system through Fibre Channel (FC) or iSCSI.
* The latency must be minimum between the WFA server and the storage system.
* The FC link must be active, and the LUNs that are created must be accessible to both the cluster nodes.
* A minimum of two network interfaces must be set up on each system: one for node-to-node communication and the other for node-to-client communication.
* The name of the network interface used for node-to-client communication should be the same on both the systems.
* A separate heartbeat link must be established between the cluster nodes; otherwise, the network interface is used to communicate between the cluster nodes.
* A shared location must be created for high availability.
+
You can use SnapDrive for UNIX to create the shared location.
+
You can also manage the LUNs using SnapDrive or the storage system command-line interface. See the SnapDrive for UNIX compatibility matrix for more information.

.Steps
. Verify that VCS is installed correctly:
+
`hastatus –summary`
+
Both the nodes must be online, and the VCS service must be running on both the nodes.

. Verify that the LUNs are accessible to both the nodes by using one of the following options:
 ** Manage the LUNs natively.
 ** Use SnapDrive for UNIX:
  .. Install SnapDrive for UNIX on both the nodes.
  .. Configure SnapDrive for UNIX on both nodes.
  .. From the first node, run the `snapdrive storage create` command to create a LUN.
  .. Verify that the LUN created on the first node is visible on the second node by running the `snapdrive storage show –all` command.
