---
permalink: rhel-install/task_upgrading_from_wfa_4_2.html
sidebar: sidebar
keywords: oncommand workflow automation, upgrading, oncommand workflow automation, 3.1 or later
summary: "You can perform an in-place upgrade from OnCommand Workflow Automation (WFA) 3.1 or later to the latest available version of WFA to use the new features and enhancements."
---
= Upgrading from OnCommand Workflow Automation 3.1 or later
:icons: font
:imagesdir: ../media/

[.lead]
You can perform an in-place upgrade from OnCommand Workflow Automation (WFA) 3.1 or later to the latest available version of WFA to use the new features and enhancements.

*What you'll need*

You must have downloaded the .bin binary file from the NetApp Support Site to the WFA host machine.

*About this task*

You can restore to WFA 5.0 from either WFA 4.2 or 4.1 only. A WFA database backup can only be restored to a system that is running the same version or a later version of WFA.

You cannot install MYSQL on your own when upgrading from earlier versions of WFA. You can install MySQL on your own:

* When you are upgrading from WFA 4.2 to later versions of WFA.
* Upgrade from WFA 3.1 or later by choosing one of the following methods:
 ** Interactive installation
  . Navigate to the `.bin` binary file in the WFA host machine, and then run the file.
  . Follow the on-screen instructions to complete the upgrade.
 ** Silent installation
+
At the shell prompt:
+
`./WFA-version_number-build_number.bin [-y] [-u admin_user_name] [-p admin_user_password]`
+
*Example:*
+
`./WFA-3.1-Z3234343435.bin -y -u admin -p Company*234`
+
During the silent upgrade, you must include values for all of the following command options:

  *** `-y` skips the installation confirmation.
  *** `-u` specifies the admin user name.
  *** `-p` specifies the admin user password.
+
If you have not provided the admin user password, then you must enter the password when prompted.
