---
permalink: rhel-install/task-reset-the-admin-password-created-during-installation-linux.html
sidebar: sidebar
keywords: reset, admin password, created, installation
summary: "If you have forgotten the password of the admin user that you created when installing the OnCommand Workflow Automation (WFA) server, you can reset it."
---
= Reset the admin password created during installation
:icons: font
:imagesdir: ../media/

[.lead]
If you have forgotten the password of the admin user that you created when installing the OnCommand Workflow Automation (WFA) server, you can reset it.

*What you'll need*

* You must have root privileges for the Linux system on which you have installed WFA.
* The WFA services must be running.

*About this task*

* This procedure resets only the password of the admin user created during the WFA installation.
+
You cannot reset the password of other WFA admin users that you created after the WFA installation.

* This procedure does not enforce the password policy you have configured.
+
Therefore, you must enter a password that complies with your password policy or change the password from the WFA user interface after you have reset the password.

.Steps
. As a root user, log in to the Linux system on which WFA is installed.
. At the shell prompt, navigate to the following directory on the WFA server:
+
`` WFA_install_location/wfa/bin/``
. Enter the following command:
+
`./wfa --admin-password [--password=PASS]`
+
If you have not provided a password, you must enter the password when prompted.

. At the shell prompt, follow the on-screen instructions.
