---
permalink: rhel-install/task_configuring_wfa_with_vcs_using_configuration_scripts_linux.html
sidebar: sidebar
keywords: configure, workflow automation, vcs
summary: "After you install Workflow Automation (WFA) in VCS, you must configure WFA in VCS using configuration scripts for high availability."
---
= Configuring Workflow Automation in VCS
:icons: font
:imagesdir: ../media/

[.lead]
After you install Workflow Automation (WFA) in VCS, you must configure WFA in VCS using configuration scripts for high availability.

*What you'll need*

* You must have installed the same version of WFA on both the cluster nodes.
* You must have the same installation path for both the nodes.
* You must create a backup of WFA.

.Steps
. Log in to the first node of the cluster.
. Use Cluster Manager to verify that the HA state of both nodes is *running*.
. At the shell prompt, run the ha_setup.pl script to move the WFA data to the shared location and to configure WFA with VCS for failover:
+
`perl ha_setup.pl --first [-t type_of_cluster_vcs] [-g cluster_group_name] [-e NIC_card_name] [-i IP_address] [-m Netmask] [-n cluster_name] [-f mount_point_of_shared_LUN] [-v name_of_logical_volume] [-d disk_group_name] [-l install_directory]`
+
For the default installation location, the script is available at `/opt/netapp/wfa/bin/ha/`.
+
*Example*
+
`perl ha_setup.pl --first -t vcs -g WFA -e eth0 -i 10.238.170.3 -m 255.255.255.0 -n wfa_cluster -f /mnt/wfa_mount/ -v lun_volume -d lun_dg -l /opt/netapp/wfa`

. Use Cluster Manager to verify that the WFA services, mount point, virtual IP, NIC, and volume group are added to the cluster group.
. Use Cluster Manager to move the WFA resources to the secondary node:
 .. Select and right-click the cluster group.
 .. Select *Switch To* > *Secondary Node*.
. Verify that the data mount, virtual IP, volume group, and NIC cards are up on the second node of the cluster.
. Take the WFA services offline by using Cluster Manager:
 .. Select *WFA* > *Application* > *wfa-server*.
 .. Right-click and select *Offline*.
 .. Select *WFA* > *Application* > *wfa-db*.
 .. Right-click and select *Offline*.
. At the shell prompt, run the ha_setup.pl script on the secondary node of the cluster to configure WFA to use the data from the shared location:
+
`perl ha_setup.pl --join [-t type_of_cluster_vcs] [-f mount_point_of_shared_LUN]`
+
For the default installation location, the script is available at `/opt/netapp/wfa/bin/ha/`.
+
*Example*
+
`perl ha_setup.pl --join -t vcs -f /mnt/wfa_mount/`

. Go to Cluster Manager and click *Cluster Group* > *Online* > *Server*.
+
It might take a while before Cluster Manager shows that the application resources are online. You can also right-click the application resources and verify whether the resources are online.

. Ensure that WFA is accessible through the IP address used during this configuration.
