---
permalink: rhel-install/task_modifying_the_default_password_policy_linux.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Workflow Automation \(WFA\) is configured to enforce a password policy for local users. You can modify the default password policy.'
---
= Modifying the default password policy
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Workflow Automation (WFA) is configured to enforce a password policy for local users. You can modify the default password policy.

You must have logged in to the WFA host system as a root user.

* The default WFA installation path is used in this procedure.
+
If you changed the default location during installation, you must use the changed WFA installation path.

* The command for the default password policy is ./wfa --password-policy=default.
+
The default is "`minLength=true,6;specialChar=true,1;digitalChar=true,1;lowercaseChar=true,1;uppercaseChar=true,1;whitespaceChar=false`" . This indicates that the default password policy must have a minimum length of 6 characters, must contain at least 1 special character, 1 digit, 1 lowercase character, 1 uppercase character, and no spaces.

. At the shell prompt, navigate to the following directory on the WFA server: WFA_install_location/wfa/bin/
. Modify the default password policy by entering the following command: `./wfa --password-policy=PasswordPolicyString --restart=WFA`
