---
permalink: rhel-install/task_configuring_an_earlier_version_of_wfa_to_high_availability.html
sidebar: sidebar
keywords: 
summary: 'You can configure OnCommand Workflow Automation \(WFA\) versions earlier than 3.1 for high availability.'
---
= Configuring an earlier version of OnCommand Workflow Automation for high availability
:icons: font
:imagesdir: ../media/

You can configure OnCommand Workflow Automation (WFA) versions earlier than 3.1 for high availability.

. Upgrade the existing version of WFA to the latest available version of WFA.
+
link:task_upgrading_from_wfa_4_2.md#[Upgrading WFA]
+
This upgraded version of WFA is the primary node of the cluster.

. Create a backup of the WFA database.
+
link:reference_backing_up_of_the_oncommand_workflow_automation_database.md#[Backing up the WFA database]
+
If any of the parameters were changed manually, you must create a backup of the WFA database, uninstall the existing WFA installation, install the latest available version of WFA, restore the backup, and then proceed with the Veritas Cluster Server (VCS) configuration.

. Configure VCS to install WFA on the primary node.
+
xref:task_configuring_vcs_to_install_wfa.adoc[Configuring VCS to install WFA]

. Install the latest available version of WFA on the secondary node.
+
xref:task_installing_oncommand_workflow_automation.adoc[Installing WFA]

. Configure WFA in VCS.
+
link:task_configuring_wfa_with_vcs_using_configuration_scripts_linux.md#[Configuring WFA in VCS]
+
The WFA server is configured for high availability.
