---
permalink: rhel-install/task_backing_up_the_wfa_database_and_configurations_linux.html
sidebar: sidebar
keywords: 
summary: 'You can back up and restore the OnCommand Workflow Automation \(WFA\) database and supported configurations so that you can recover the data in case of a disaster. The supported configurations include data access, HTTP timeout, and SSL certificates.'
---
= Backing up and restoring the OnCommand Workflow Automation database and configurations on Linux
:icons: font
:imagesdir: ../media/

You can back up and restore the OnCommand Workflow Automation (WFA) database and supported configurations so that you can recover the data in case of a disaster. The supported configurations include data access, HTTP timeout, and SSL certificates.

You must have administrator privileges or architect credentials.

You must create the backup in a secure location because restoring the backup will provide access to all the storage systems that are accessed by WFA.

NOTE:

* A comprehensive backup of WFA databases and configurations is required during disaster recovery and can be used in both standalone and high-availability environments.
* You can use only the CLI commands or REST APIs for comprehensive backup and restore operations during disaster recovery.
+
You cannot use the web UI for backing up or restoring the WFA database during disaster recovery.

. Back up the OnCommand Workflow Automation database.
+
link:reference_backing_up_of_the_oncommand_workflow_automation_database.md#[Backing up the OnCommand Workflow Automation database]

. Restore a previous backup of the OnCommand Workflow Automation database.
+
link:concept_restoring_the_wfa_database.md#[Restoring the OnCommand Workflow Automation database]
