---
permalink: rhel-install/task_modifying_the_transaction_timeout_setting_of_oncommand_workflow_automation_linux.html
sidebar: sidebar
keywords: modify, transaction, timeout, setting, oncommand workflow automation
summary: "The OnCommand Workflow Automation (WFA) database transaction times out in 300 seconds by default. You can increase the default timeout duration when restoring a large-sized WFA database from a backup to avoid potential failure of the database restoration."
---
= Modifying the transaction timeout setting of OnCommand Workflow Automation
:icons: font
:imagesdir: ../media/

[.lead]
The OnCommand Workflow Automation (WFA) database transaction times out in 300 seconds by default. You can increase the default timeout duration when restoring a large-sized WFA database from a backup to avoid potential failure of the database restoration.

*What you'll need*

You must have logged in to the WFA host system as a root user.

*About this task*

The default WFA installation path is used in this procedure. If you changed the default location during installation, you must use the changed WFA installation path.

.Steps
. At the shell prompt, navigate to the following directory on the WFA server:
+
`WFA_install_location/wfa/bin/`
. Enter the following command:
+
`./wfa --txn-timeout[=TIMEOUT] --restart=WFA`
+
*Example*
+
`./wfa --txn-timeout=1000 --restart=WFA`
