---
permalink: rhel-install/task-install-oncommand-workflow-automation.html
sidebar: sidebar
keywords: oncommand workflow automation, install, linux
summary: "You can install OnCommand Workflow Automation (WFA) by using the command-line interface (CLI)."
---
= Install OnCommand Workflow Automation on Linux
:icons: font
:imagesdir: ../media/

[.lead]
You can install OnCommand Workflow Automation (WFA) by using the command-line interface (CLI).

.What you'll need

* You must have reviewed the installation prerequisites.
+
xref:reference-prerequisites-for-installing-workflow-automation.adoc[Installation prerequisites]

* You must have downloaded the WFA installer from the NetApp Support Site.

.About this task

If you are installing WFA on a virtual machine (VM), the name of the VM must not include the underscore (_) character.

You can change the default installation location at the shell prompt:

`./WFA-version_number.bin [-i WFA_install_directory] [-d mysql_data_directory]`

If you change the default installation location, the MySQL data directory is not deleted when you uninstall WFA. You must manually delete the directory.

NOTE: Before reinstalling WFA 4.2 or later, you must delete the MySQL data directory if you have uninstalled MySQL.

.Steps
. Log in to the Linux server as a `root` user.
. Navigate to the directory where the executable `.bin` file is located.
. Install WFA by choosing one of the following methods:
 ** Interactive installation
  .. Start the interactive session: `./WFA-version_number.bin`
  .. Enter the credentials for the default admin user, and then press Enter.
+
You must note the credentials for the admin user and ensure that the password meets the following criteria:

   **** Minimum of six characters
   **** One uppercase character
   **** One lowercase character
   **** One numeral
   **** One special character

  .. Accept the default ports for WFA configuration or provide custom ports, and then press Enter.
  .. Specify your company name and a site name, and then press Enter.
+
The site name can include the location of the WFA installation, for example, Pittsburgh, PA.

  .. Verify that WFA is installed successfully by choosing one of the following actions:
   **** Access WFA through a web browser.
   **** Verify that the NetApp WFA Server service and the NetApp WFA Database service are running:
   +
  `service wfa-server status`
   +
  `service wfa-db status`
 ** Silent installation
+
At the shell prompt:
+
`./WFA-version_number.bin [-u admin_user_ name] [-p admin_user_password] [-m https_port] [-n http_port] [-c company_name] [-s site_name] [-i install_directory] [-d mysql_data_directory][-y] [-b]`
+
If you want to perform a silent installation, you must specify values for all of the command options. The command options are as follows:
+
[cols="2*",options="header"]
|===
| Option| Description
a|
-y
a|
Option to skip

Skips the installation confirmation
a|
-b
a|
Option to skip

Skips creating a backup of the WFA database during an upgrade
a|
-u
a|
Admin user name
a|
-p
a|
Admin user password

The admin user password must satisfy the following criteria:

  *** Minimum of six characters
  *** One uppercase character
  *** One lowercase character
  *** One numeral
  *** One special character
a|
-m
a|
HTTPS port
a|
-n
a|
HTTP port
a|
-s
a|
Site name
a|
-c
a|
Company name
a|
-i
a|
Installation directory path
a|
-d
a|
MySQL data directory
a|
-h
a|
Option to display

Displays the Help
|===

*Related information*

http://mysupport.netapp.com[NetApp Support^]
