---
settings:
  name: OnCommand Workflow Automation 5.0
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: OnCommand Workflow Automation 5.0 docs
      url: "/index.html"
    - title: Release Notes
      url: "/reference-releasenotes.html"
    - section: rhel-install
    - section: windows-install
    - section: help
    - section: workflows
    - title: Legal notices
      url: "/legal-notices.html"
homepage:
  tiles:
    - title: Get started
      links:
        - title: Release Notes
          url: reference-releasenotes.html
    - title: Install and setup on Linux systems
      links:
        - title: System requirements for installing OnCommand Workflow Automation
          url: rhel-install/reference-system-requirements-for-oncommand-workflow-automation-linux.html
        - title: Manage high availability
          url: rhel-install/concept-managing-high-availability.html
        - title: Set up OnCommand Workflow Automation
          url: rhel-install/concept-set-up-oncommand-workflow-automation.html
        - title: Back up the OnCommand Workflow Automation database
          url: rhel-install/reference-backing-up-of-the-oncommand-workflow-automation-database.html
        - title: Restore the OnCommand Workflow Automation database
          url: rhel-install/concept-restoring-the-wfa-database.html
        - title: Uninstall OnCommand Workflow Automation
          url: rhel-install/task-uninstall-oncommand-workflow-automation-linux.html
        - title: Troubleshoot installation and configuration issues
          url: rhel-install/reference-troubleshooting.html
    - title: Install and setup on Windows systems
      links:
        - title: System requirements for installing OnCommand Workflow Automation
          url: windows-install/reference-system-requirements-for-oncommand-workflow-automation-windows.html
        - title: Install OnCommand Workflow Automation on Windows
          url: windows-install/task-install-workflow-automation-on-windows.html
        - title: Set up OnCommand Workflow Automation
          url: windows-install/concept-setting-up-oncommand-workflow-automation.html
        - title: Back up the OnCommand Workflow Automation database
          url: windows-install/reference-backing-up-of-the-oncommand-workflow-automation-database.html
        - title: Restore the OnCommand Workflow Automation database
          url: windows-install/concept-restoring-the-wfa-database.html
        - title: Uninstall OnCommand Workflow Automation
          url: windows-install/task-uninstall-oncommand-workflow-automation.html
        - title: Troubleshoot installation and configuration issues
          url: windows-install/reference-troubleshooting.html
    - title: Build and manage workflows
      links:
        - title: Managing workflows
          url: workflows/concept-managing-workflows.html
    - title: More information
      links:
        - title: NetApp community
          url: http://community.netapp.com/t5/OnCommand-Storage-Management-Software-Articles-and-Resources/tkb-p/oncommand-storage-management-software-articles-and-resources/label-name/workflow%20automation%20%28wfa%29?labels=workflow+automation+%28wfa%29[^]
        - title: Interoperability Matrix
          url: http://mysupport.netapp.com/matrix/[^]
