settings:
  search: workflow-automation-50
sidebar:
  entries:
    - title: Workflow Automation Documentation
      url: "/index.html"
    - section: help
    - section: rhel-install
    - section: windows-install
    - section: workflows
    - title: Legal notices
      url: "/legal-notices.html"
