---
settings:
  name: OnCommand Workflow Automation 5.0.1
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: OnCommand Workflow Automation 5.0.1 docs
      url: "/index.html"
    - title: Release Notes
      url: "/reference-releasenotes.html"
    - section: rhel-install
    - section: windows-install
    - section: help
    - section: workflows
    - title: Legal notices
      url: "/legal-notices.html"
