---
settings:
  search: workflow-automation-50
sidebar:
  entries:
    - title: Home
      url: "/index.html"
    - section: rhel-install
    - section: windows-install
    - section: workflows
    - title: Legal notices
      url: "/legal-notices.html"
