---
settings:
  name: OnCommand Workflow Automation 5.0
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: OnCommand Workflow Automation 5.0 docs
      url: "/index.html"
    - title: Release Notes
      url: "/reference-releasenotes.html"
    - section: rhel-install
    - section: windows-install
    - section: help
    - section: workflows
    - title: Legal notices
      url: "/legal-notices.html"
homepage:
  tiles:
    - title: Get started
      links:
        - title: Release Notes
          url: reference-releasenotes.html
    - title: Install & setup
      links:
        - title: Install OnCommand Workflow Automation on Linux systems
          url: rhel-install/concept_oncommand_workflow_automation_installation_and_configuration_instructions.html
        - title: Install OnCommand Workflow Automation on Windows
          url: windows-install/concept_oncommand_workflow_automation_installation_and_configuration_instructions.html
    - title: Build and manage workflows
      links:
        - title: Managing workflows
          url: workflows/concept_managing_workflows.html
