---
permalink: windows-install/reference_ports_required_for_oncommand_workflow_automation.html
sidebar: sidebar
keywords: 
summary: 'If you are using a firewall, you must be aware of the required ports for Workflow Automation \(WFA\).'
---
= Ports required for Workflow Automation
:icons: font
:imagesdir: ../media/

[.lead]
If you are using a firewall, you must be aware of the required ports for Workflow Automation (WFA).

The default port numbers are listed in this section. If you want to use a non-default port number, you must open that port for communication. For more details, see the documentation on your firewall.

The following table lists the default ports that should be open on the WFA server:

|===
| Port| Protocol| Direction| Purpose
a|
80, 443
a|
HTTP, HTTPS
a|
Incoming
a|
Opening WFA and logging in
a|
80, 443, 22
a|
HTTP, HTTPS, SSH
a|
Outgoing
a|
Command execution (ZAPI, PowerCLI)
a|
445, 139, 389, 636
a|
Microsoft-DS, NetBIOS-ssn, AD LDAP, AD LDAPS
a|
Outgoing
a|
Microsoft Active Directory LDAP authentication
a|
161
a|
SNMP
a|
Outgoing
a|
Sending SNMP messages on the status of workflows
a|
3306
a|
MySQL
a|
Incoming
a|
Caching read-only user
a|
25
a|
SMTP
a|
Outgoing
a|
Mail notification
a|
80, 443, 25
a|
HTTP, HTTPS, SMTP
a|
Outgoing
a|
Sending AutoSupport messages
a|
514
a|
Syslog
a|
Outgoing
a|
Sending logs to a syslog server
|===
The following table lists the default ports that should be open on the Data Center Manager server:

|===
| Port| Protocol| Direction| Purpose
a|
2638
a|
Sybase
a|
Incoming
a|
Caching data from Active IQ Data Center Manager earlier than 6.0
a|
3306
a|
MySQL
a|
Incoming
a|
Caching data from Active IQ Data Center Manager 6.0 and later
a|
8088, 8488
a|
HTTP, HTTPS
a|
Incoming
a|
Caching data from Performance Advisor, which is a part of Active IQ Data Center Manager earlier than 6.0
|===
The following table lists the default port that should be open on the VMware vCenter:

|===
| Port| Protocol| Direction| Purpose
a|
443
a|
HTTPS
a|
Incoming
a|
Caching data from VMware vCenter
|===
The following table lists the default port that should be open on the SNMP host machine:

|===
| Port| Protocol| Direction| Purpose
a|
162
a|
SNMP
a|
Incoming
a|
Receiving SNMP messages on the status of workflows
|===
