---
permalink: windows-install/reference_wfa_displays_a_blank_page_on_windows_2012.html
sidebar: sidebar
keywords: 
summary: 'A blank page might be displayed if you have downloaded and installed Adobe Flash Player separately from the Adobe website. You must not download and install the Flash Player separately because it is bundled with Internet Explorer in Windows 2012. Updates for the Flash Player are installed through Windows updates.'
---
= OnCommand Workflow Automation (WFA) displays a blank page on Windows 2012
:icons: font
:imagesdir: ../media/

A blank page might be displayed if you have downloaded and installed Adobe Flash Player separately from the Adobe website. You must not download and install the Flash Player separately because it is bundled with Internet Explorer in Windows 2012. Updates for the Flash Player are installed through Windows updates.

If you have downloaded and installed the Flash Player separately, you must perform the following steps:

. Uninstall the Flash Player that you have already installed.
. In Windows, open *Server Manager* > *Local Server* > *ROLES AND FEATURES* > *TASKS* and select *Add Roles and Features*.
. In the Add Roles and Features Wizard, click *Features* > *User Interface and Infrastructure*, select *Desktop Experience* and then complete adding the feature.
+
Adding Desktop Experience adds the Flash Player to Windows.

. Restart Windows.
