---
permalink: windows-install/reference_cannot_view_performance_advisor_data_in_wfa.html
sidebar: sidebar
keywords: cannot view, performance, advisor, data, wfa
summary: "If you cannot view Performance Advisor data in WFA or if the data acquisition process from the Performance Advisor data source fails, you should perform certain actions to troubleshoot the issue."
---
= Cannot view Performance Advisor data in WFA
:icons: font
:imagesdir: ../media/

[.lead]
If you cannot view Performance Advisor data in WFA or if the data acquisition process from the Performance Advisor data source fails, you should perform certain actions to troubleshoot the issue.

* Ensure that you have specified the credentials of an Active IQ Data Center Manager user with a minimum role of GlobalRead when configuring Performance Advisor as a data source in WFA.
* Ensure that you have specified the correct port when configuring Performance Advisor as a data source in WFA.
+
By default, Active IQ Data Center Manager uses port 8088 for an HTTP connection and port 8488 for an HTTPS connection.

* Ensure that performance data is collected by the Active IQ Data Center Manager server.
