---
permalink: windows-install/reference_backing_up_of_the_oncommand_workflow_automation_database.html
sidebar: sidebar
keywords: back up, oncommand workflow automation, database
summary: "A backup of the OnCommand Workflow Automation (WFA) database includes the system configuration settings and cache information, including the playground database. You can use the backup for restoration purposes on the same system or on a different system."
---
= Backing up the OnCommand Workflow Automation database
:icons: font
:imagesdir: ../media/

[.lead]
A backup of the OnCommand Workflow Automation (WFA) database includes the system configuration settings and cache information, including the playground database. You can use the backup for restoration purposes on the same system or on a different system.

An automatic backup of the database is created daily at 2 a.m. and is saved as a `.zip` file in the following location: `wfa_install_location/WFA-Backups`.

WFA saves up to five backups in the WFA-Backups directory, and replaces the oldest backup with the latest backup. The WFA-Backups directory is not deleted when you uninstall WFA. You can use the automatically created backup for restoration if you did not create a backup of the WFA database while uninstalling WFA.

You can also manually back up the WFA database when you have to save specific changes for restoration; for example, if you want to back up the changes that you have made before the automatic backup occurs.

[NOTE]
====
* You can restore a WFA database backup only to a system that is running the same version or a later version of WFA.
+
For example, if you created a backup on a system that is running WFA 4.2, the backup can be restored only to systems that are running WFA 4.2 or later.

* You cannot use the web UI to back up the WFA database during disaster recovery in a high-availability setup.
====
== Backup and restoration of user credentials

The backup of the WFA database includes the WFA user credentials.

NOTE: The WFA database is also included in the AutoSupport (ASUP) data; however, the password of any WFA user is not included in the ASUP data.

When a WFA database is restored from a backup, the following items are preserved:

* The admin user credentials that were created during the current WFA installation.
* If a user with admin privileges other than the default admin user restores the database, the credentials of both the admin users.
* All other user credentials of the current WFA installation are replaced with the user credentials from the backup.
