---
permalink: windows-install/task_enable_remote_access_to_the_oncommand_workflow_automation_database.html
sidebar: sidebar
keywords: enable, remote, access, oncommand workflow automation, database, windows
summary: "By default, the OnCommand Workflow Automation (WFA) database can be accessed only by clients that are running on the WFA host system. You can change the default settings if you want to access the WFA database from a remote system."
---
= Enable remote access to the OnCommand Workflow Automation database on Windows
:icons: font
:imagesdir: ../media/

[.lead]
By default, the OnCommand Workflow Automation (WFA) database can be accessed only by clients that are running on the WFA host system. You can change the default settings if you want to access the WFA database from a remote system.

*What you'll need*

* You must have logged in to the WFA host system as an admin user.
* If a firewall is installed on the WFA host system, you must have configured your firewall settings to allow access from the remote system.

*About this task*

The default WFA installation path is used in this procedure. If you changed the default location during installation, you must use the custom WFA installation path.

. Open Windows Explorer, and navigate to the following directory: `WFA_install_location\WFA\bin`
. Perform one of the following actions:
+
[cols="2*",options="header"]
|===
| To...| Enter the following command...
a|
Enable remote access
a|
`.\wfa --db-access=public --restart`
a|
Disable remote access
a|
`.\wfa --db-access=default --restart`
|===
