---
permalink: windows-install/task_installing_workflow_automation_on_windows.html
sidebar: sidebar
keywords: OnCommand Workflow Automation
summary: 'You can install OnCommand Workflow Automation \(WFA\) to create and customize storage workflows for automating the storage tasks that are performed in your environment.'
---
= Installing OnCommand Workflow Automation on Windows
:icons: font
:imagesdir: ../media/

You can install OnCommand Workflow Automation (WFA) to create and customize storage workflows for automating the storage tasks that are performed in your environment.

* You must have reviewed the installation prerequisites.
+
xref:reference_prerequisites_for_installing_workflow_automation.adoc[Prerequisites for installing Workflow Automation]

* If you are installing WFA on a system where WFA was previously installed and then uninstalled, you must ensure that there are no WFA services on that system.
* You must have downloaded the WFA installer from the NetApp Support Site.
* You must disable the `Auto upgrade` feature of Java.
* If you are installing WFA on a virtual machine (VM), the name of the VM must not include the underscore (_) character.
* ActiveState ActivePerl is installed before you install WFA.
+
This installation does not affect any other instances of ActivePerl that you have installed on your WFA server.

* Before you reinstall WFA 4.2 or later, you must delete MySQL data directory if you have uninstalled MySQL.
* If you install MySQL on your own, WFA sets the secure-file-privilege and the sql-mode properties in MySQL my.ini file to blank.

. Log in to Windows using an account with administrative permissions.
. Open Windows Explorer, and then navigate to the directory where the installation file is located.
. Install WFA:
 ** Interactive installation
  ... Right-click and run the WFA installer executable (.exe) file as an admin user.
  ... Click *Next*.
  ... Enter the credentials for the default admin user, and then click *Next*.
+
The default admin password must satisfy the following criteria:

   **** Minimum of six characters
   **** One uppercase character
   **** One lowercase character
   **** One numeral
   **** One special character
*Note:* You must note the credentials of the admin user.

  ... Select the ports for the WFA configuration, and then click *Next*.
  ... Enter a site name and your company name, and then click *Next*.
+
The site name can include the location of the WFA installation, for example, Pittsburgh, PA.

  ... If you want to change the default installation location, select the location where you want to install WFA, and then click *Next*.
  ... If you do not want to change the default location of the WFA database, click *Next*.
  ... Click *Install* to continue the installation.
  ... Click *Finish* to complete the installation.
  ... Verify that WFA was installed successfully by choosing one of the following actions:
   **** Access WFA through a web browser.
   **** Use the Windows Services console to verify that the NetApp WFA Server service and the NetApp WFA Database service are running.
 ** Silent installation (from the command prompt):WFA-version_number-build_number.exe /s /v"WFA_ADMIN_USERNAME=wfa_username WFA_ADMIN_PASSWORD=password WFA_ADMIN_CONFIRM_PASSWORD=confirm admin password / WFA_MYSQL_PASS=password CONFIRM_WFA_MYSQL_PASS=confirm MySQL password WFA_INSTALL_SITE=site WFA_INSTALL_ORGANIZATION=organization_name WFA_HTTP_PORT=port WFA_HTTPS_PORT=port INSTALLDIR=install_directory DATABASEDIR=database_directory /qr /l*v C:\install.log"
+
**Example**WFA-x64-v4.2.0.0.0-B2973881.exe /s /v"WFA_ADMIN_USERNAME=admin WFA_ADMIN_PASSWORD=Company*234 WFA_ADMIN_CONFIRM_PASSWORD=Company*234 WFA_MYSQL_PASS=MySQL*234 CONFIRM_WFA_MYSQL_PASS=MySQL*234 WFA_INSTALL_SITE=nb WFA_INSTALL_ORGANIZATION=netapp WFA_HTTP_PORT=9090 WFA_HTTPS_PORT=8443 INSTALLDIR=\"C:\Program Files\NetApp\WFA\" DATABASEDIR=\"C:\Program Files\NetApp\WFA\Database\" /qr /l*v C:\install.log"
+
NOTE: The /qn option is not supported by WFA.
+
The command parameters are as follows:
+
|===
| Parameter| Description
a|
WFA_ADMIN_USERNAME
a|
Admin user name        Optional parameter. If you do not specify a value, then the default value admin is used.
a|
WFA_ADMIN_PASSWORD
a|
Admin user password        Mandatory parameter. The default admin password must satisfy the following criteria:

  *** Minimum of six characters
  *** One uppercase character
  *** One lowercase character
  *** One numeral
  *** One special character

a|
WFA_ADMIN_CONFIRM_PASSWORD
a|
Admin user password        Mandatory parameter
a|
WFA_MYSQL_PASS
a|
MySQL user password         Mandatory parameter
a|
CONFIRM_WFA_MYSQL_PASS
a|
MySQL user password        Mandatory parameter
a|
WFA_INSTALL_SITE
a|
Organizational unit where WFA is being installed        Mandatory parameter
a|
WFA_INSTALL_ORGANIZATION
a|
Organization or company name where WFA is being installed        Mandatory parameter
a|
WFA_HTTP_PORT
a|
HTTP port        Optional parameter. If you do not specify a value, then the default value 80 is used.
a|
WFA_HTTPS_PORT
a|
HTTPS port        Optional parameter. If you do not specify a value, then the default value 443 is used.
a|
INSTALLDIR
a|
Installation directory path        Optional parameter. If you do not specify a value, then the default path "C:\Program Files\NetApp\WFA\" is used.
+
|===

*Related information*

xref:task_upgrading_oncommand_workflow_automation.adoc[Upgrading OnCommand Workflow Automation]

xref:reference_prerequisites_for_installing_workflow_automation.adoc[Prerequisites for installing Workflow Automation]

http://mysupport.netapp.com[NetApp Support]
