---
permalink: windows-install/task-upgrade-jre-on-windows-wfa.html
sidebar: sidebar
keywords: oncommand workflow automation, upgrade, jre
summary: "You can upgrade new versions of Java Runtime Environment (JRE) to OnCommand Workflow Automation (WFA) on the Windows server. You can upgrade to a newer version of JRE to get fixes for security vulnerabilities on the Windows server."
---
= Upgrade JRE
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade new versions of Java Runtime Environment (JRE) to OnCommand Workflow Automation (WFA) on the Windows server. You can upgrade to a newer version of JRE to get fixes for security vulnerabilities on the Windows server.

.What you'll need

You must have Windows admin privileges on the WFA server.

.About this task

You can update JRE releases within release families. For example, you can upgrade from Java 8 update 144 (64 bit) to Java 8 update 151 (64 bit), but you cannot update directly from Java 8 to Java 9.

.Steps
. Log in as the admin user on the WFA host machine.
. Download and install the latest version of Java 8 64-bit from the Oracle site to the target system.
. Use the Windows Services console to stop the following WFA services:
 ** NetApp WFA Database or MYSQL57
 ** NetApp WFA Server
. Click `updateWFARegistry.vbs` from the `<installdir>\WFA\bin\` path to update the latest version of JRE in the WFA registry.
+
*Example*
+
----
C:\Program Files\NetApp\WFA\bin>cscript.exe
updateWFARegistry.vbs
Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved
C:\Program Files\NetApp\WFA\bin>
----

. Start the WFA services by using the Windows Services console.
