---
permalink: windows-install/task-modify-the-default-password-policy-windows.html
sidebar: sidebar
keywords: modify, default, password, policy, windows
summary: "OnCommand Workflow Automation (WFA) enforces a password policy for local users. You can modify the default password policy to set a password as per your requirement."
---
= Modify the default password policy for Windows
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Workflow Automation (WFA) enforces a password policy for local users. You can modify the default password policy to set a password as per your requirement.

*What you'll need*

You must be logged in to the WFA host system as a root user.

*About this task*

* The default WFA installation path is used in this procedure.
+
If you changed the default location during installation, you must use the custom WFA installation path.

* The command for modifying the default password policy is `.\wfa --password-policy=default.`
+
The default setting is "`minLength=true,6;specialChar=true,1;digitalChar=true,1;lowercaseChar=true,1;uppercaseChar=true,1;whitespaceChar=false`". Per this setting for the default password policy, the password must have a minimum length of six characters, must contain at least one special character, one digit, one lowercase character, and one uppercase character, and must not contain spaces.

.Steps
. At the command prompt, navigate to the following directory on the WFA server:
+
`WFA_install_location/wfa/bin/`
. Modify the default password policy:
+
`.\wfa --password-policy=PasswordPolicyString --restart=WFA`
