---
permalink: windows-install/task_disabling_the_default_password_policy.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Workflow Automation \(WFA\) is configured to enforce a password policy for local users. If you do not want to use the password policy, you can disable it.'
---
= Disabling the default password policy
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Workflow Automation (WFA) is configured to enforce a password policy for local users. If you do not want to use the password policy, you can disable it.

You must have logged in to the WFA host system as an admin.

The default WFA installation path is used in this procedure. If you changed the default location during installation, you must use the changed WFA installation path.

. Open Windows Explorer and navigate to the following directory: WFA_install_location\WFA\bin\.
. Double-click the ps.cmd file.
+
A PowerShell command-line interface (CLI) prompt opens with ONTAP and WFA modules loaded in it.

. At the prompt, enter the following: `Set-WfaConfig -Name PasswordPolicy -Enable $false`
. When prompted, restart the WFA services.
