---
permalink: windows-install/task_configure_an_earlier_version_of_wfa_foir_high_availability_windows.html
sidebar: sidebar
keywords: configure, earlier, versions, oncommand workflow automation, high, availability
summary: "You can configure OnCommand Workflow Automation (WFA) versions earlier than 3.1 for high availability."
---
= Configure earlier versions of OnCommand Workflow Automation for high availability
:icons: font
:imagesdir: ../media/

[.lead]
You can configure OnCommand Workflow Automation (WFA) versions earlier than 3.1 for high availability.

.Steps
. Upgrade the existing version of WFA to the latest available version of WFA.
+
link:task_upgrade_oncommand_workflow_automation.html[Upgrade WFA]
+
This upgraded version of WFA is the primary node of the cluster.

. Create a backup of the WFA database.
+
link:reference_backing_up_of_the_oncommand_workflow_automation_database.html[Backing up the WFA database]
+
If any of the parameters were changed manually, you must create a backup of the WFA database, uninstall the existing WFA installation, install the latest available version of WFA, restore the backup, and then proceed with the Microsoft Cluster Service (MSCS) configuration.

. Configure MSCS to install WFA on the primary node.
+
link:task_configure_mscs_to_install_wfa.html[Configure MSCS to install WFA]

. Install the latest available version of WFA on the secondary node.
+
link:task_install_workflow_automation_on_windows.html[Install WFA]

. Configure WFA in MSCS.
+
link:task_configure_mscs_to_install_wfa.html[Configure WFA in MSCS]
+
The WFA server is configured for high availability.
