---
permalink: windows-install/task-migrate-oncommand-workflow-automation.html
sidebar: sidebar
keywords: migrate, oncommand workflow automation, installation
summary: "You can migrate an OnCommand Workflow Automation (WFA) installation to maintain the unique WFA database key that is installed during the WFA installation. For example, you can migrate the WFA installation from a Windows 2008 server to a Windows 2012 server."
---
= Migrate the OnCommand Workflow Automation installation
:icons: font
:imagesdir: ../media/

[.lead]
You can migrate an OnCommand Workflow Automation (WFA) installation to maintain the unique WFA database key that is installed during the WFA installation. For example, you can migrate the WFA installation from a Windows 2008 server to a Windows 2012 server.

*About this task*

* You must perform this procedure only when you want to migrate a WFA installation that includes the WFA database key to a different server.
* A WFA database restore does not migrate the WFA key.
* Migrating a WFA installation does not migrate the SSL certificates.
* The default WFA installation path is used in this procedure.
+
If you changed the default location during installation, you must use the changed WFA installation path.

.Steps
. Access WFA through a web browser as an admin.
. Back up the WFA database.
. Open a command prompt on the WFA server and change directories to the following location: `c:\Program Files\NetApp\WFA\bin`
. Enter the following at the command prompt to obtain the database key: `wfa.cmd -key`
. Note the database key that is displayed.
. Uninstall WFA.
. Install WFA on the required system.
. Open the command prompt on the new WFA server and change directories to the following location: `c:\Program Files\NetApp\WFA\bin`
. Enter the following at the command prompt to install the database key: `wfa.cmd -key=yourdatabasekey`
+
_yourdatabasekey_ is the key that you noted from the previous WFA installation.

. Restore the WFA database from the backup that you created.
