---
permalink: windows-install/task_repairing_the_activeperl_installation.html
sidebar: sidebar
keywords: repairing, activeperl, installation
summary: "ActiveState ActivePerl is installed on your OnCommand Workflow Automation (WFA) server when you install WFA. ActivePerl is required for the execution of Perl commands. If you inadvertently uninstall ActivePerl from the WFA server or if the ActivePerl installation is corrupted, you can manually repair the ActivePerl installation."
---
= Repairing the ActivePerl installation
:icons: font
:imagesdir: ../media/

[.lead]
ActiveState ActivePerl is installed on your OnCommand Workflow Automation (WFA) server when you install WFA. ActivePerl is required for the execution of Perl commands. If you inadvertently uninstall ActivePerl from the WFA server or if the ActivePerl installation is corrupted, you can manually repair the ActivePerl installation.

.Steps
. Back up the WFA database using one of the following options:
 ** WFA web portal
 ** PowerShell script
. Uninstall WFA.
. Install the version of WFA that you uninstalled.
+
ActivePerl is installed when you install WFA.

. Restore the WFA database.

*After you finish*

You can review the restored content for completeness in functionality--for example, the functioning of your custom workflows.
