---
permalink: windows-install/task_backing_up_regular_the_wfa_database_using_perl_script_linux.html
sidebar: sidebar
keywords: OnCommand Workflow Automation
summary: 'You can perform a regular backup of the OnCommand Workflow Automation \(WFA\) database by using the WFA command-line interface \(CLI\). In a regular backup, only the WFA database is backed up.'
---
= Backing up (regular) the WFA database using the CLI
:icons: font
:imagesdir: ../media/

[.lead]
You can perform a regular backup of the OnCommand Workflow Automation (WFA) database by using the WFA command-line interface (CLI). In a regular backup, only the WFA database is backed up.

You must have admin user credentials, architect credentials, or backup user credentials.

In a high-availability environment, you should create scheduled backups by using REST APIs. You cannot create backups by using the CLI when WFA is in failover mode.

For more information, see the REST documentation.

. At the shell prompt, navigate to the following directory on the WFA server: WFA_install_location\WFA\bin.
+
WFA_install_location is the WFA installation directory.

. Back up the WFA database: `.\wfa --backup --user=USER [--password=PASS] [--location=PATH]`
 ** user is the user name of the backup user.
 ** password is the password of the backup user.
+
If you have not provided the password, you must enter the password when prompted.

 ** path is the complete directory path to the backup file.
. Verify that the backup file was created at the specified location.
