---
permalink: windows-install/task_configuring_wfa_with_mscs_using_configuration_scripts.html
sidebar: sidebar
keywords: configuring, workflow, automation, mscs
summary: "After you install Workflow Automation (WFA) in Microsoft Cluster Server (MSCS), you must configure WFA for high availability in MSCS using configuration scripts."
---
= Configuring Workflow Automation with MSCS
:icons: font
:imagesdir: ../media/

[.lead]
After you install Workflow Automation (WFA) in Microsoft Cluster Server (MSCS), you must configure WFA for high availability in MSCS using configuration scripts.

*What you'll need*

You must have created a backup of WFA.

.Steps
. Log in to the first node of the MSCS cluster, and perform the following steps:
+
[cols="2*",options="header"]
|===
| For...| Do this...
a|
Windows 2012
a|

 .. From the Failover Cluster Manager, right-click *Service Roles*.
 .. Select *Create Empty Service Role*, and then rename the role to "`WFA`".
 .. Add the IP address resource to the newly created "`WFA`" role:
  ... From the Failover Cluster Manager, right-click the newly created "`WFA`" role.
  ... Select *Resource* > *More Resources* > *IP Address*.
  ... Configure the cluster IP address.

a|
Windows 2008
a|

 .. From the Failover Cluster Manager, right-click *Services and applications*.
 .. Click *More Actions* > *Create Empty Service or Application*, and rename the service to "`WFA`".
 .. Add the IP address resource to the newly created "`WFA`" service:
  ... From the Failover Cluster Manager, right-click the newly created "`WFA`" service.
  ... Select *Add a resource* > *More resources* > *Add IP Address*.
  ... Configure the cluster IP address.

+
|===

. At the command prompt, run the `ha_setup.pl` script to move the WFA data to the shared location and to configure WFA with MSCS for failover: `perl ha_setup.pl --first [-t type_of_cluster_vcs] [-g cluster_group_name] [-i IP_address_resource_name] [-n cluster_name] [-k shared_disk_resource_name] [-f shared_drive_path]`
+
The script is available at `WFA_install_location\WFA\bin\ha\.`
+
*Example*
+
`perl ha_setup.pl --first -t mscs -g WFA -i "Cluster IP Address" -n wfa_cluster -k "Cluster Disk 2" -f E:\`

. Verify that the MSCS resources are created.
. Stop the WFA services from the Failover Cluster Manager:
+
|===
| For...| Do this...
a|
Windows 2012
a|

 .. Select *Service Roles*, and then select the newly created "`WFA`" role.
 .. In the Resource pane, right-click *NA_WFA_DB*, and then select *Take Offline*.
 .. In the Resource pane, right-click *NA_WFA_SRV*, and then select *Take Offline*.

a|
Windows 2008
a|

 .. Select *Services and applications*, and then select the newly created "`WFA`" service.
 .. In the Other Resources pane, right-click *NA_WFA_DB*, and then select *Take this resource offline*.
 .. In the Other Resources pane, right-click *NA_WFA_SRV*, and then select *Take this resource offline*.

+
|===
The WFA database service and the WFA server service must be taken offline. The WFA services must not be stopped from the Windows services.

. Manually move the WFA resources to the secondary node.
. Verify that the shared disk is accessible from the second node.
. At the command prompt, run the ha_setup.pl script on the secondary node of the cluster to configure WFA for using the data from the shared location: `perl ha_setup.pl --join [-t type_of_cluster_mscs] [-f shared_drive_path]`
+
The `ha_setup.pl` script is available at `WFA_install_location\WFA\bin\ha\.`
+
*Example*
+
`perl ha_setup.pl --join -t mscs -f E:\`

. From the Failover Cluster Manager, bring the WFA resources online:
+
[cols="2*",options="header"]
|===
| For...| Do this...
a|
Windows 2012
a|

 .. Right-click the newly created "`WFA`" role, and then select *Start Role*.
 The role must be in the Running status, and the individual resources must be in the Online state.

a|
Windows 2008
a|

 .. Right-click the newly created "`WFA`" service, and then select *Bring this service or application online*.
 The service must be in the `Running` status, and the individual resources must be in the `Online` state.

+
|===

. Manually switch to the second node of the MSCS cluster.
. Verify that the WFA services start properly on the second node of the cluster.
