---
permalink: windows-install/task-upgrade-mysql-on-windows-wfa.html
sidebar: sidebar
keywords: oncommand workflow automation, upgrade, mysql
summary: "You can upgrade new versions of MySQL for OnCommand Workflow Automation (WFA) on the Windows server. You can upgrade to a newer version of MySQL to get fixes for security vulnerabilities on the Windows server."
---
= Upgrade MySQL
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade new versions of MySQL for OnCommand Workflow Automation (WFA) on the Windows server. You can upgrade to a newer version of MySQL to get fixes for security vulnerabilities on the Windows server.

*What you'll need*

You must have Windows admin privileges and the password for MYSQL root user on the WFA server.

NOTE: Before reinstalling WFA 4.2 or later, you must have deleted the MySQL data directory if you have uninstalled MySQL.

*About this task*

You should be aware of the following limitations:

* You can upgrade within any version of MySQL 5.7.
+
For example, you can upgrade from MySQL 5.7.1 to MySQL 5.7.2.

* You cannot upgrade from MySQL 5.7 to MySQL 5.8

.Steps
. Log in as the admin user on the WFA host machine.
. Download the appropriate version of MySQL to the target system.
. Use the Windows Services console to stop the following WFA services:
 ** NetApp WFA Database or MYSQL57
 ** NetApp WFA Server
. Click on the MYSQL msi package to invoke the upgrade of MySQL.
. Follow the instructions on the screen to complete MySQL installation.
. Start the WFA services by using the Windows *Services* console.
