---
permalink: windows-install/task_resetting_the_admin_password_created_during_installation.html
sidebar: sidebar
keywords: 
summary: 'If you have forgotten the password of the admin user that you created during OnCommand Workflow Automation \(WFA\) server installation, you can reset the password.'
---
= Resetting the admin password created during installation
:icons: font
:imagesdir: ../media/

[.lead]
If you have forgotten the password of the admin user that you created during OnCommand Workflow Automation (WFA) server installation, you can reset the password.

* You must have admin privileges for the Windows system on which you have installed WFA.
* The WFA services must be running.
* This procedure resets only the password of the admin user that was created during the WFA installation.
+
You cannot reset the password of other WFA admin users that you created after the WFA installation.

* This procedure does not enforce the password policy that you have configured.
+
You must either enter a password that complies with your password policy or change the password from the WFA user interface after you have reset the password.

. Open a command prompt and navigate to the following directory: WFA_install_location\WFA\bin\
. Enter the following command: `wfa --admin-password [--password=PASS]`
+
If you do not provide a password in the command, you must enter the password when prompted.

. At the command prompt, follow the on-screen instructions to reset the admin password.
