---
permalink: windows-install/task_configuring_authentication_settings.html
sidebar: sidebar
keywords: OnCommand Workflow Automation
summary: 'You can configure OnCommand Workflow Automation \(WFA\) to use a Microsoft Active Directory \(AD\) Lightweight Directory Access Protocol \(LDAP\) server for authentication and authorization.'
---
= Configuring authentication settings
:icons: font
:imagesdir: ../media/

[.lead]
You can configure OnCommand Workflow Automation (WFA) to use a Microsoft Active Directory (AD) Lightweight Directory Access Protocol (LDAP) server for authentication and authorization.

You must have configured a Microsoft AD LDAP server in your environment.

Only Microsoft AD LDAP authentication is supported for WFA. You cannot use any other LDAP authentication methods, including Microsoft AD Lightweight Directory Services (AD LDS) or Microsoft Global Catalog.

NOTE: During communication, LDAP sends the user name and password in plain text. However, LDAPS (LDAP secure) communication is encrypted and secure.

. Log in to WFA through a web browser as an admin.
. Click *Settings*, and under *Setup* click *Authentication*.
. Select the *Enable Active Directory* check box.
. Enter the required information in the fields:
 .. If you want to use the user@domain format for domain users, replace sAMAccountName with userPrincipalName in the *User name attribute* field.
 .. If unique values are required for your environment, edit the required fields.
 .. Enter the AD server URI as follows: `ldap://active_directory_server_address\[:port\]`
+
ldap://NB-T01.example.com[:389]
+
If you have enabled LDAP over SSL, you can use the following URI format: `ldaps://active_directory_server_address\[:port\]`

 .. Add a list of AD group names the required roles.
+
NOTE: You can add a list of AD group names to the required roles in the Active Directory Groups Window.
. Click *Save*.
. If LDAP connectivity to an array is required, configure the WFA service to log on as the required domain user:
 .. Open the Windows services console by using services.msc.
 .. Double-click the *NetApp WFA Server* service.
 .. In the NetApp WFA Server Properties dialog box, click the *Log On* tab, and then select *This account*.
 .. Enter the domain user name and password, and then click *OK*.
