---
permalink: help/concept_how_you_use_the_rest_api.html
sidebar: sidebar
keywords: use, rest, apis, how to
summary: "You can use REST APIs provided by Workflow Automation (WFA) to invoke workflows from external portals and the data center orchestration software. WFA supports XML and JSON content types for all REST APIs."
---
= How you use REST APIs
:icons: font
:imagesdir: ../media/

[.lead]
You can use REST APIs provided by Workflow Automation (WFA) to invoke workflows from external portals and the data center orchestration software. WFA supports XML and JSON content types for all REST APIs.

WFA allows external services to access various resource collections, such as workflows, users, filters, and finders, through URI paths. The external services can use HTTP methods, such as GET, PUT, POST, and DELETE, on these URIs to perform CRUD operations on the resources.

You can perform several actions through the WFA REST APIs, including the following:

* Access workflow definitions and metadata.
* Execute workflows and monitor their execution.
* View users and roles, and change passwords.
* Execute and test resource selection filters.
* Execute and test resource finders.
* Manage credentials of storage or other data center objects.
* View data sources and data source types.

_REST documentation_ has more information about REST APIs:

https://wfa_server_ip:port/rest/docs

`wfa_server_ip` is the IP address of your WFA server and port is the TCP port number you have used for the WFA server during installation.
