---
permalink: help/concept_how_you_define_workflows.html
sidebar: sidebar
keywords: how to, define, workflows
summary: "You must break down the goal of a workflow into the steps that should be executed by the workflow. You can then arrange the steps to complete your workflow."
---
= How you define workflows
:icons: font
:imagesdir: ../media/

[.lead]
You must break down the goal of a workflow into the steps that should be executed by the workflow. You can then arrange the steps to complete your workflow.

A workflow is an algorithm that includes a series of steps that are required to complete an end-to-end process. The scope of the process might vary, depending on the goal of the workflow. The goal of a workflow might be defined to handle only storage operations or more complex processes such as handling networking, virtualization, IT systems, and other applications as part of a single process. OnCommand Workflow Automation (WFA) workflows are designed by storage architects and are executed by storage operators.

Defining your workflow includes breaking down the goal of your workflow into a series of steps--for example, creating an NFS volume includes the following steps:

. Creating a volume object
. Creating a new export policy and associating the policy with the volume

You can use a WFA command or a workflow for each step in your workflow. WFA includes predefined commands and workflows, which are based on common storage use cases. If you do not find a predefined command or workflow that can be used for a particular step, you can do one of the following:

* Choose a predefined command or workflow that closely matches the step, and then clone and modify the predefined command or workflow according to your requirements.
* Create a new command or workflow.

You can then arrange the commands or workflows in a new workflow to create the workflow that accomplishes your goal.

At the beginning of the workflow execution, WFA plans the execution and verifies that the workflow can be executed using the input to the workflow and the commands. When planning the workflow, all resource selection and user input are resolved to create an execution plan. After planning is completed, WFA executes the execution plan, which consists of a set of WFA commands with applicable parameters.
