---
permalink: help/reference_backup_restore_window.html
sidebar: sidebar
keywords: backup and restore, window
summary: "The Backup and Restore window enables you to back up the OnCommand Workflow Automation (WFA) database, which contains the system configuration settings, cache information, and core packs that include PowerShell toolkits and Perl toolkits. You can also restore the saved database when you upgrade or reinstall WFA."
---
= Backup and Restore window
:icons: font
:imagesdir: ../media/

[.lead]
The Backup and Restore window enables you to back up the OnCommand Workflow Automation (WFA) database, which contains the system configuration settings, cache information, and core packs that include PowerShell toolkits and Perl toolkits. You can also restore the saved database when you upgrade or reinstall WFA.

== Backup section

You can access this window by selecting *Settings*, and under *Maintenance* click *Backup & Restore*.

* *Backup*
+
Opens the File Download dialog box, which enables you to save the current database as a compressed file to a specified location.

== Restore section

* *Choose File*
+
Enables you to search for the backup database file.

* *Restore*
+
Enables you to reinstate the configuration settings and cache information from the backup database file to the current WFA configuration, if applicable.
+
The latest version of the toolkits and core packs are available after a restore operation.
+
NOTE: If backup includes newer packs than the packs present on the system, the after restore the newer packs from backup are available.
+
You must stop any workflows that are running before you import a core pack.
