---
permalink: help/reference-clone-finder-dialog-box.html
sidebar: sidebar
keywords: clone finder, dialog box
summary: "The Clone Finder dialog box enables you to create a copy of the finder and edit the cloned finder."
---
= Clone Finder dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Clone Finder dialog box enables you to create a copy of the finder and edit the cloned finder.

* Properties tab
* Filters
* Returned Attributes tab

== Properties tab

The Properties tab enables you to edit the name of the finder, the type of object, and the description for the finder. The tab also displays the input parameters of the filter used in the finder.

* *Name*
+
Enables you to edit the name of the finder. The name of the finder you have selected to clone is used as the name for the clone and appended with `- copy` by default.

* *Type*
+
Enables you to select the type of object from the list. The filters for the selected object are displayed in the Filters tab.

* *Entity Version*
+
Enables you to enter the version number for the finder in _major.minor.revision_ format--for example, 1.0.0.

* *Description*
+
Enables you to edit the description for the finder.

* *Input Parameters table*
+
Displays the input parameters of the selected filters.

== Filters tab

Enables you to select the required filters from the available list of filters.

* *Available Filters*
+
Displays the list of available filters for the selected object in the Properties tab.

* *Selected Filters*
+
Displays the list of filters selected from the available filters.

* *Selection buttons*
+
Enables you to move the selected entry from one box to another.

== Returned Attributes tab

Enables you to see the details of the available filters, select the required attributes of available filters, and specify the sort order for the attributes.

* *Available*
+
Displays the available filters and the attributes for the filters.

* *Selected*
+
Displays the selected filters and the attributes, the aliases, and the sort order for the selected filters.

* *Command buttons*
 ** *Up*
+
Moves the selected entry up one row in the Selected table.

 ** *Down*
+
Moves the selected entry down one row in the Selected table.

 ** *Selection buttons*
+
Moves the selected entry from one table to another.

== Command buttons

* *Test*
+
Enables you to test the finder that you have selected to clone.

* *Save*
+
Saves the finder and closes the dialog box.

* *Cancel*
+
Cancels changes, if any, and closes the dialog box.
