---
permalink: help/reference_row_repetition_details_dialog_box.html
sidebar: sidebar
keywords: 
summary: 'The Row Repetition Details dialog box enables you to specify how the parameters in the row should be repeated.'
---
= Row Repetition Details dialog box
:icons: font
:imagesdir: ../media/

The Row Repetition Details dialog box enables you to specify how the parameters in the row should be repeated.

== Repeats

Enables you to select the required type of repeat option. The *Number of times* option is selected by default.

* *Number of times*
+
Enables you to specify the following:

 ** The number of times the specific row should be executed
 ** Index Variable
 ** Variables
 ** *Number of Times*
+
Enables you to specify a numeral for the number of times the specific row should be executed.

 ** *Index Variable*
+
Enables you to specify the name of the index variable for row repetition.

 ** *Variables*
+
Enables you to include additional variables that have to be used during row repetition.

  *** *Add*
+
Adds a new row in the variables table.

  *** *Remove*
+
Removes the selected row from the variables table.

* *For every resource in a group*
+
Enables you to specify the following:

 ** Resource Type
 ** Resource Search Criteria
 ** Resource Variable
 ** Index Variable
 ** Group Size Variable
 ** Variables
 ** *Resource Type*
+
Enables you to select the resource type.

 ** *Resource Search Criteria*
+
Opens the Resource Selection dialog box, which enables you to specify the criteria for searching resources of the selected resource type. The loop is executed for each searched resource based on the specified criteria.

 ** *Resource Variable*
+
Enables you to enter a name for the resource variable.

 ** *Index Variable*
+
Enables you to specify the index for row repetition.

 ** *Group Size Variable*
+
Enables you to enter a name for the group size variable.

 ** *Variables*
+
Enables you to include additional variables that have to be used during row repetition.

* *Command buttons*
 ** *OK*
+
Saves the settings and closes the dialog box.

 ** *Cancel*
+
Does not save any changes, if any, and closes the dialog box.
