---
permalink: help/reference_edit_user_dialog_box.html
sidebar: sidebar
keywords: 
summary: 'The Edit User dialog box enables you to view and modify user account settings.'
---
= Edit User dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Edit User dialog box enables you to view and modify user account settings.

Depending on your account privileges and role, you might not have access to the Users window. However, you can edit the settings for your account by selecting *Settings*, and under *Management* click *Account Settings*.

NOTE: The fields that are available to you for editing depend on your assigned role and account privileges.

* *Name*
+
Displays the user name for the user account.

* *Role*
+
Displays the assigned role for the user account.

* *E-mail*
+
Specifies the email for the user account to which notifications are sent if a Notify On option is selected.

* *Change password*
+
Enables you to change the current password for the user account. When this check box is selected, the following fields are required:

 ** *New Password*--Specifies the new password.
 ** *Confirm*--Specifies the new password again.

* *Notify On*
+
Enables you to select when the account user should be notified by email during the workflow execution. When this check box is selected, you can select any combination of the following options:

 ** Workflow execution started: Notifies the user when the workflow execution begins.
 ** Workflow execution failed/partially successful: Notifies the user if the workflow execution fails or if workflow has been successfully executed even if one or more steps have failed.
+
The execution is completed because the failed steps have been configured such that the workflow execution continues even when the step has failed.

 ** Workflow execution completed successfully: Notifies the user when the workflow execution is completed successfully.
 ** Workflow execution waiting for approval: Notifies the user if the workflow execution is waiting for approval from either an Operator or Architect user, depending on the WFA configuration setting.
 ** Acquisition failure: Notifies the user when data acquisition for data sources fails.
+
This option is enabled only for Admin and Architect users.

== Command buttons

* *Save*
+
Saves the configuration settings and closes the dialog box.

* *Cancel*
+
Cancels changes, if any, and closes the dialog box.
