---
permalink: help/reference_edit_active_directory_group_dialog_box.html
sidebar: sidebar
keywords: edit active directory group, dialog box
summary: "The Edit Active Directory Group dialog box enables you to view and modify the OnCommand Workflow Automation Active Directory group settings."
---
= Edit Active Directory Group dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Edit Active Directory Group dialog box enables you to view and modify the OnCommand Workflow Automation Active Directory group settings.

Depending on your Active Directory group privileges and role, you might not have access to the Active Directory Groups window. However, you can edit the settings for your Active Directory group by selecting *Settings*, and under *Management* click *Active Directory Groups*.

NOTE: The fields that are available to you for editing depend on your Active Directory group privileges.

* *Group Name*
+
Displays the group name for the Active Directory group.

* *Role*
+
Displays the assigned role for the user account.
+
Displays one of the following group roles assigned for the Active Directory group:

 ** *Guest*
+
This group can only view the status of a workflow execution or be notified about a change in the status of a workflow execution.

 ** This group is allowed to preview and execute the workflows for which the group is provided access.
 ** *Approver*
+
This group is allowed to preview, execute, approve, and reject the workflows for which the group is provided access.
+
NOTE: You must provide the email ID of the approver and the status of the workflow that is to be notified to the approver. If there are multiple approvers, you can provide a group email ID in the *E-mail* field.

 ** *Architect*
+
This group has full access to create workflows, but is restricted from modifying global WFA server settings.

 ** *Admin*
+
This group has complete access to the WFA server.
+
NOTE: You must configure at least one admin group.

* *E-mail*
+
Specifies the email for the Active Directory group to which notifications are sent if the *Notify On* option is selected.

* *Notify On*
+
Enables you to select when the active directory group should be notified by email during the workflow execution triggered by that active directory group. You can select any combination of the following options:

 ** Workflow execution started: Notifies the user when the workflow execution begins.
 ** Workflow execution failed/partially successful: Notifies the user if the workflow execution fails or if the workflow was successfully executed even though one or more steps failed.
+
The execution is completed because the failed steps were configured to allow the workflow execution to continue even when the step fails.

 ** Workflow execution completed successfully: Notifies the user when the workflow execution is completed successfully.
 ** Workflow execution waiting for approval: Notifies the user if the workflow execution is waiting for approval from either an Operator or Architect user, depending on the WFA configuration setting.

== Command buttons

* *Save*
+
Saves the configuration settings and closes the dialog box.

* *Cancel*
+
Cancels changes, if any, and closes the dialog box.
