---
permalink: help/reference_new_filter_dialog_box.html
sidebar: sidebar
keywords: new filter, dialog box
summary: "You can use the New Filter dialog box to create a new filter. You can use the filter to develop finders."
---
= New Filter dialog box
:icons: font
:imagesdir: ../media/

[.lead]
You can use the New Filter dialog box to create a new filter. You can use the filter to develop finders.

* Properties tab
* Query tab

== Properties tab

The *Properties* tab enables you to specify a name for the filter, select a dictionary object, and enter a description for the filter.

* *Name*
+
Enables you to enter a name for the filter.

* *Type*
+
Enables you to select a dictionary object from the list.

* *Entity Version*
+
Enables you to enter the version number for the filter in major.minor.revision format--for example, 1.0.0.

* *Description*
+
Enables you to enter a description for the filter.

== Query tab

Enables you to enter an SQL query, and edit the label and the description for the attributes.

* *SQL Query*
+
Enables you to enter an SQL query for the filter.

* *Input Parameters table*
+
Displays the list of parameters from the SQL query that you have entered which require user input when the filter is used. You can click the *Label* or the *Description* column of a parameter to edit the label or enter a description.

* *Returned Attributes table*
+
Displays the list of returned attributes from the SQL query.

== Command buttons

* *Test*
+
Enables you to test the filter that you have defined.

* *Refresh*
+
Populates the *Input Parameters* table and the *Returned Attributes* table with changed values, if any.

* *Save*
+
Saves the filter and closes the dialog box.

* *Cancel*
+
Does not save the filter and closes the dialog box.
