---
permalink: help/reference_clone_category_dialog_box.html
sidebar: sidebar
keywords: 
summary: 'The Clone Category dialog box enables you to copy a workflow category and edit the category.'
---
= Clone Category dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Clone Category dialog box enables you to copy a workflow category and edit the category.

* *Name*
+
Enables you to edit the name for the category. The name of the category you have selected to clone is used as the name for the clone and appended with - copy by default.

* *Description*
+
Enables you to enter a description for the category.

* *Available Workflows*
+
Displays all the available workflows that are not moved to the Selected Workflows box.

* *Selected Workflows*
+
Displays all the workflows you have selected for the category.

* *Category Used for Workflow Authorization*
+
Enables you to select users with operator role who can execute the category. By default, the check box is not selected and the category is available for all users.

* *Available Operators*
+
Displays all the users with operator role.

* *Selected Operators*
+
Displays the users who are allowed to execute the category.

== Command buttons

* *Selection buttons*
+
Enables you to move the selected entry from one box to another.

* *Save*
+
Saves the category and closes the dialog box.

* *Cancel*
+
Does not save the category and closes the dialog box.
