---
permalink: help/reference-mvel-enabled-fields-in-wfa.html
sidebar: sidebar
keywords: mvel-enabled fields, oncommand workflow automation
summary: "Several fields in OnCommand Workflow Automation (WFA) are enabled for MVFLEX Expression Language (MVEL). You can use MVEL syntaxes in these fields while designing workflows."
---
= MVEL-enabled fields in OnCommand Workflow Automation
:icons: font
:imagesdir: ../media/

[.lead]
Several fields in OnCommand Workflow Automation (WFA) are enabled for MVFLEX Expression Language (MVEL). You can use MVEL syntaxes in these fields while designing workflows.

The following table explains when and where you can use MVEL syntaxes in the WFA interface:

[cols="2*",options="header"]
|===
| When...| Where to use...
a|
Creating or editing a workflow
a|

* *Workflow* > *Details* > *Return Parameters* > *Parameter Value*
* *Workflow* > *Details* > *Constants* > *Value*

a|
Creating or editing command details in a workflow
a|

* *Commands* > *Parameters for _parameter_name_* > *Enter search criteria* > *Resource Selection* > *Finder* > *Parameters*
* *Commands* > *Parameters for _parameter_name_* > *Enter search criteria* > *Resource Selection* > *Advanced* > *Execute search only when the following expression evaluates to TRUE*
* *Commands* > *Parameters for _parameter_name_* > *Advanced* > *If the following expression is TRUE*
* *Commands* > *Parameters for _parameter_name_* > *Other Parameters*
* *Commands* > *parameter_name* > *Attributes*

a|
Creating or editing a command
a|

* *Commands* > *Command Definition _command_name_* > *Properties* > *String Representation*

a|
Creating or editing a function
a|

* *Functions* > *Function _function_name_* > *Function definition*

a|
Creating or editing a template
a|

* *Template* > *Parameters for _parameter_name_* > *Template _template_name_* > *Attributes* > *Value*

a|
Editing a row
a|

* *Workflow* > *Workflow* > *Repeat row* > *Repeats* > *Number of times*
* *Workflow* > *Workflow* > *Repeat row* > *Variables* > *Variables for _initial_value_ and expression*
* *Workflow* > *Workflow* > *Repeat row* > *Repeats* > *For every resource in a group* > *Resource Search Criteria* > *Parameters to filter*
* *Workflow* > *Workflow* > *Add condition* > *If the following expression is TRUE*
|===
