---
permalink: help/reference_clone_filter_dialog_box.html
sidebar: sidebar
keywords: clone filter, dialog box
summary: "The Clone Filter dialog box enables you to copy a filter and edit the filter."
---
= Clone Filter dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Clone Filter dialog box enables you to copy a filter and edit the filter.

* Properties tab
* Query tab

== Properties tab

The *Properties* tab enables you to edit the name of the filter, select a dictionary object, and edit the description for the filter.

* *Name*
+
Enables you to edit the name of the filter. The name of the filter you have selected to clone is used as the name for the clone and appended with _copy by default.

* *Dictionary type*
+
Enables you to select a dictionary object from the list.

* *Entity Version*
+
Enables you to enter the version number for the filter in _major.minor.revision_ format--for example, 1.0.0.

* *Description*
+
Enables you to edit the description for the filter.

== Query tab

Enables you to edit the SQL query, the label, and the description for the attributes.

* *SQL Query*
+
Enables you to edit the SQL query of the filter.

* *Input Parameters table*
+
Displays the list of parameters from the SQL query that you have entered which require user input when the filter is used. You can click the *Label* or the *Description* column of a parameter to edit the label or the description.

* *Returned Attributes table*
+
Displays the list of returned attributes from the SQL query.

== Command buttons

* *Test*
+
Enables you to test the filter.

* *Refresh*
+
Populates the**Input Parameters** table and the *Returned Attributes* table with changed values, if any.

* *Save*
+
Saves the filter and closes the dialog box.

* *Cancel*
+
Does not save the filter and closes the dialog box.
