---
permalink: help/reference_edit_category_dialog_box.html
sidebar: sidebar
keywords: 
summary: 'The Edit Category dialog box enables you to edit a workflow category.'
---
= Edit Category dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Edit Category dialog box enables you to edit a workflow category.

* *Name*
+
Enables you to edit the name of the category.

* *Description*
+
Enables you to edit the description for the category.

* *Available Workflows*
+
Displays all the available workflows that are not moved to the Selected Workflows box.

* *Selected Workflows*
+
Displays all the workflows that are selected for the category.

* *Category Used for Workflow Authorization*
+
Enables you to grant access to users with operator role to execute the category. The check box is not selected by default.

* *Available Operators*
+
Displays all the users with operator role who do not have access to the category.

* *Selected Operators*
+
Displays the users who are granted access to the category.

== Command buttons

* *Selection buttons*
+
Moves the selected entry from one box to another.

* *Save*
+
Saves the category and closes the dialog box.

* *Cancel*
+
Does not save the category and closes the dialog box.
