---
permalink: help/reference-edit-remote-system-type-dialog-box.html
sidebar: sidebar
keywords: edit remote system type, dialog box
summary: "The Edit Remote System Type dialog box enables you to modify the name, description, version, protocol, default port, and default timeout of an existing remote system type. You cannot modify a NetApp-certified remote system type."
---
= Edit Remote System Type dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Edit Remote System Type dialog box enables you to modify the name, description, version, protocol, default port, and default timeout of an existing remote system type. You cannot modify a NetApp-certified remote system type.

* Details tab
* Validation Script tab

== Details tab

Enables you to edit the details of the remote system type, such as the name, description, version, and connection protocol.

* *Name*
+
Enables you to edit the name of the remote system type.

* *Description*
+
Enables you to modify the description of the remote system type.

* *Version*
+
Enables you to edit the version number of the remote system type in _major.minor.revision_ format--for example, 1.0.0.

* *Connection Protocol*
+
Enables you to select one of the following protocols that should be used by OnCommand Workflow Automation (WFA) when connecting to the remote system:

 ** HTTPS with fallback to HTTP
+
The connection primarily uses HTTPS. If connection through HTTPS fails, HTTP is used. If connection through HTTP also fails, the connection attempt is dropped.

 ** HTTPS Only
 ** HTTP Only
 ** Custom
+
When you select a connection protocol, the protocol, default port, and default timeout (sec) fields are populated with data.

== Validation Script tab

Enables you to provide a validation script to test the connectivity of the remote system. The validation script must be written in Perl and must include the following function: checkCredentials(`$host, $user, $password, $protocol, $port, $timeout`). During validation, WFA calls the checkCredentials function with the values that are configured for the remote system type and the connection protocol. The function returns the value "`1`" on successful validation of connectivity or "`0`" on failure of connection validation.

You can click *Test Perl Script* to run the script for testing the connectivity.

== Command buttons

* *Save*
+
Saves the modified configuration settings of the remote system type and closes the dialog box.

* *Cancel*
+
Cancels changes, if any, and closes the dialog box.
