---
permalink: help/reference_incremental_naming_wizard.html
sidebar: sidebar
keywords: 
summary: 'The Incremental Naming Wizard enables you to define the value of an attribute based on a search for an existing parameter.'
---
= Incremental Naming Wizard
:icons: font
:imagesdir: ../media/

The Incremental Naming Wizard enables you to define the value of an attribute based on a search for an existing parameter.

* *Search criteria for existing <dictionary object>*
+
Opens the *Resource Selection* dialog box, which enables you to specify a search criteria for the dictionary object.

* *Enter a value for <attribute> if no <dictionary object> matches the above search criteria*
+
Enables you to specify a value for the <attribute> when the <dictionary object> is not found using the specified search criteria.

* *If <dictionary object> was found using above search criteria, set value for <attribute> by*
+
Enables you to specify a value for the <attribute> when the <dictionary object> is not found using the specified search criteria.

* *Enter a value for <attribute> if no <dictionary object> matches the above search criteria*
+
Enables you to select a method for setting the value for the <attribute> if the <dictionary object> is found using the specified search criteria.

 ** *providing an increment value and suffix*
+
Enables you to enter a numeric value for the increments and optionally enter a suffix of the attribute name.

 ** *providing a custom expression*
+
Enables you to enter a custom expression for the value of the attribute. You can use MVFLEX Expression Language (MVEL) syntax to specify the value.
