---
permalink: help/reference_clone_template_dialog_box.html
sidebar: sidebar
keywords: clone template, dialog box
summary: "The Clone Template dialog box enables you to create a copy of the template and edit the template."
---
= Clone Template dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Clone Template dialog box enables you to create a copy of the template and edit the template.

* *Name*
+
Enables you to edit the name of the template.

* *Type*
+
Enables you to select a dictionary object from the list. The name of the template you have selected to clone is used as the name for the clone and appended with - copy by default.

* *Entity Version*
+
Enables you to enter the version number for the template in major.minor.revision format--for example, 1.0.0.

* *Description*
+
Enables you to edit the description for the template.

* *Attributes*
+
Displays the attributes for the selected dictionary object and enables you to enter a value for each attribute, such as enum and function.

== Command buttons

* *Save*
+
Saves the template and closes the dialog box.

* *Cancel*
+
Does not save the template and closes the dialog box.
