---
permalink: help/reference_new_credentials_dialog_box.html
sidebar: sidebar
keywords: 
summary: 'The New Credentials dialog box enables you to create a new credential.'
---
= New Credentials dialog box
:icons: font
:imagesdir: ../media/

The New Credentials dialog box enables you to create a new credential.

== Credential parameters

You can set the following parameters for the newly created credential:

* *Match*
+
Enables you to select the match type of the credential, which defines the credential for either a specific IP address or host name, or an entire subnet or IP range. You can select one of the following options:

 ** Exact: defines credentials for a specific IP or host name
 ** Pattern: defines credentials for the host name range or the entire subnet or IP range
+
Pattern is a regular expression that is used for matching a string. For example, `10.10.10.*` matches any IP in the range 10.10.10.0 through 10.10.10.255, and `host*` matches all host names starting with `host`.

* *Type*
+
Enables you to select the host type from the drop-down list.
+
NOTE: VMware vCenter is not supported for Linux.

* *Name/IP*
+
Enables you to specify the host name or IP address for the credential.

* *User Name*
+
Enables you to specify a user name for the credential.

* *Password*
+
Enables you to specify a password for the user name that you created for the credential.

* *Overwrite Default Values*
+
Enables you to overwrite the default values of the protocol, port, and timeout that are associated with the selected remote system type for the credential.
+
By default, this check box is not selected. You must select the check box if you want to overwrite the default values.

== Command buttons

* *Test*
+
Enables you to test the connection to the host or IP address by logging in using the required credentials.

* *Save*
+
Saves the configuration settings and closes the dialog box.

* *Cancel*
+
Cancels changes, if any, and closes the dialog box.

*Related information*

xref:reference_credentials_window.adoc[Credentials window]
