---
permalink: help/reference_new_remote_system_type_dialog_box.html
sidebar: sidebar
keywords: new, remote, system, type, dialog box
summary: "The New Remote System Type dialog box enables you to add a new remote system type to OnCommand Workflow Automation (WFA) if a predefined system type does not meet your requirement or if you want to change the configuration of a predefined system type."
---
= New Remote System Type dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The New Remote System Type dialog box enables you to add a new remote system type to OnCommand Workflow Automation (WFA) if a predefined system type does not meet your requirement or if you want to change the configuration of a predefined system type.

* Details tab
* Validation Script tab

== Details tab

Enables you to specify the details of the remote system type, such as the name, description, version, and connection protocol.

* *Name*
+
Enables you to specify a name for the remote system type. You must specify a name in order to save the remote system type.

* *Description*
+
Enables you to enter a description for the remote system type.

* *Version*
+
Enables you to specify the version number for the remote system type in major.minor.revision format--for example, 1.0.0.

* *Connection Protocol*
+
Enables you to select one of the following protocols that should be used by WFA when connecting to the remote system:

 ** HTTPS with fallback to HTTP
+
The connection primarily uses HTTPS. If connection through HTTPS fails, HTTP is used. If connection through HTTP also fails, the connection attempt is dropped.

 ** HTTPS Only
 ** HTTP Only
 ** Custom
When you select a connection protocol, the protocol, default port, and default timeout (sec) fields are populated with data.

== Validation Script tab

Enables you to test the connectivity of the selected protocol with the remote system type.

You can click *Test Perl Script* to run the script for testing the connectivity.

== Command buttons

* *Save*
+
Saves the configuration settings of the remote system type and closes the dialog box.

* *Cancel*
+
Cancels changes, if any, and closes the dialog box.
