---
permalink: help/reference_edit_filter_dialog_box.html
sidebar: sidebar
keywords: 
summary: 'The Edit Filter dialog box enables you to edit a filter.'
---
= Edit Filter dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Edit Filter dialog box enables you to edit a filter.

* <<GUID-D6561A31-8337-48C7-B20C-A3F542E78D8F,Properties tab>>
* <<SECTION_AAD904D9F3714252BA89D382F76EE560,Query tab>>

== Properties tab

The *Properties* tab enables you to edit the name of the filter, select a dictionary object, and edit the description for the filter.

* *Name*
+
Enables you to edit the name of the filter.

* *Type*
+
Enables you to select a dictionary object from the list.

* *Entity Version*
+
Enables you to enter the version number for the filter in major.minor.revision format--for example, 1.0.0.

* *Description*
+
Enables you to edit the description for the filter.

== Query tab

Enables you to edit the SQL query, the label, and the description for the attributes.

* *SQL Query*
+
Enables you to edit the SQL query of the filter.

* *Input Parameters table*
+
Displays the list of parameters from the SQL query that you have entered which require user input when the filter is used. You can click the *Label* or the *Description* column of a parameter to edit the label or the description.

* *Returned Attributes table*
+
Displays the list of returned attributes from the SQL query.

== Command buttons

* *Test*
+
Enables you to test the filter.

* *Refresh*
+
Populates the**Input Parameters** table and the *Returned Attributes* table with changed values, if any.

* *Save*
+
Saves the filter and closes the dialog box.

* *Cancel*
+
Does not save the changes, if any, and closes the dialog box.
