---
permalink: help/reference_new_user_dialog_box.html
sidebar: sidebar
keywords: 
summary: 'The New User dialog box enables you to create a new user account.'
---
= New User dialog box
:icons: font
:imagesdir: ../media/

The New User dialog box enables you to create a new user account.

* *Username*
+
Specifies the user name.

* *Role*
+
Enables you to select one of the following user roles:

 ** Guest: This user can only view the status of a workflow execution or can be notified about a change in the status of a workflow execution.
 ** Operator: This user is allowed to preview and execute workflows for which the user is provided access.
 ** Architect: This user has full access to create workflows, but is restricted from modifying global WFA server settings.
 ** Admin: This user has complete access to the WFA server.
 ** Backup: This user is the only user who can remotely generate backups of the WFA server; however, the user is restricted from all other access.

* *E-mail*
+
Enables you to specify the user's email address to which notifications are sent if the Notify On option is selected.

* *Password*
+
Specifies the password for the user.

* *Confirm*
+
Specifies the password again.

* *Notify On*
+
Enables you to select when the account user should be notified by email. The workflow execution status notifications are specific to the workflows executed by the user. You can select any combination of the following options:

 ** Workflow execution started: Notifies the user when the workflow execution begins.
 ** Workflow execution failed/partially successful: Notifies the user if the workflow execution fails or if workflow has been successfully executed even if one or more steps have failed.
+
The execution is completed because the failed steps have been configured such that the workflow execution continues even when the step has failed.

 ** Workflow execution completed successfully: Notifies the user when the workflow execution is completed successfully.
 ** Workflow execution waiting for approval: Notifies the user if the workflow execution is waiting for approval from either an Operator or Architect user, depending on the WFA configuration setting.
 ** Acquisition failure: Notifies the user when data acquisition for data sources fails.
+
This option is enabled only for Admin and Architect users.

== Command buttons

* *Save*
+
Saves the configuration settings and closes the dialog box.

* *Cancel*
+
Cancels changes, if any, and closes the dialog box.
