---
permalink: help/reference_edit_pack_dialog_box.html
sidebar: sidebar
keywords: Workflow Automation
summary: 'The Edit Pack dialog box enables you to edit the pack.'
---
= Edit Pack dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Edit Pack dialog box enables you to edit the pack.

* <<SECTION_C2EE96889E4E41608A7DB372804AAC96,Details tab>>
* <<GUID-3F785577-E761-4A2C-9AEA-813CC85646D8,Pack Contents tab>>

== Details tab

* *Name*
+
Enables you to enter a name and save the pack.

* *Version*
+
Enables you to enter a version and save the pack.

* *Author*
+
Enables you to enter author's name and save the pack.

* *Description*
+
Enables you to enter a description and save the pack.

== Pack Contents tab

* *Workflow*
+
The *Workflow* option enables you to view the *Name* and *Entity Version* of the workflow.

* *Finders*
+
The *Finders* option enables you to view the *Name* and *Entity Version* of the finder.

* *Filters*
+
The *Filters* option enables you to view the *Name* and *Entity Version* of the filter.

* *Commands*
+
The *Commands* option enables you to view the *Name* and *Entity Version* of the command.

* *Functions*
+
The *Functions* option enables you to view the *Name* and *Entity Version* of the function.

* *Templates*
+
The *Templates* option enables you to view the *Name* and *Entity Version* of the template.

* *Dictionary*
+
The *Dictionary* option enables you to view the *Name* and *Entity Version* of the dictionary.

* *Schemes*
+
The *Schemes* option enables you to view the *Name* and *Entity Version* of the scheme.

* *Cache Queries*
+
The *Cache Queries* option enables you to view the *Name* and *Entity Version* of the cache query.

* *SQL Data Source Types*
+
The *SQL Data Source Types* option enables you to view the *Name* and *Entity Version* of the SQL data source type.

* *Script Data Source Types*
+
The *Script Data Source Types* option enables you to view the *Name* and *Entity Version* of the script data source type.

* *Categories*
+
The *Categories* option enables you to view the *Name* and *Entity Version* of the category.

* *Remote System Types*
+
The *Remote System Types* option enables you to view the *Name* and *Entity Version* of the remote system type.

== Command buttons

* *Save*
+
Saves the pack and closes the dialog box.

* *Cancel*
+
Closes the dialog box without saving.
