---
permalink: help/reference-edit-approval-point-dialog-box.html
sidebar: sidebar
keywords: edit approval point, dialog box
summary: "The Edit Approval Point dialog box enables you to modify an approval point that was added as a check point in a workflow to pause the workflow execution and resume it based on your approval."
---
= Edit Approval Point dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Edit Approval Point dialog box enables you to modify an approval point that was added as a check point in a workflow to pause the workflow execution and resume it based on your approval.

* *Enter comment (optional)*
+
Enables you to provide information, such as time of change, user, and comments, which enables you to see when and why the workflow execution was paused or resumed.
+
The approval point comments can include MVFLEX Expression Language (MVEL) expressions.

* *Enter the execution condition (if any)*
+
Enables you to specify the following conditions for the execution of a command:

 ** Always
+
Executes the command unconditionally.

 ** If the following variable was found
+
Enables you to execute a command only when the specified variable is found. You can specify the variable in the box.

 ** If the following variable was not found
+
Enables you to execute a command only when the specified variable is not found. You can specify the variable in the box.

 ** If the following expression is TRUE
+
Enables you to execute a command only when the specified MVEL expression is "`true`". You can specify the expression in the box.

== Command buttons

* *Remove Approval*
+
Enables you to remove the approval point before the command is executed.

* *OK*
+
Enables you to modify the changes to the approval point settings.

* *Cancel*
+
Cancels changes, if any, and closes the dialog box.
