---
permalink: help/reference_test_connectivity_dialog_box.html
sidebar: sidebar
keywords: 
summary: 'The Test Connectivity dialog box enables you to test the connection to the system associated with a credential. The test connectivity operation triggers the search path and first looks for an exact match, then for a pattern match, and finally for LDAP service authentication.'
---
= Test Connectivity dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Test Connectivity dialog box enables you to test the connection to the system associated with a credential. The test connectivity operation triggers the search path and first looks for an exact match, then for a pattern match, and finally for LDAP service authentication.

== Test Connectivity parameters

The Internet Control Message Protocol (ICMP) is used to check if the system is running before testing for connectivity.

* *Type*
+
Enables you to select the type of credential from the drop-down list.

* *Name/IP*
+
Enables you to specify the host name or IP address for the credential.

== Command buttons

* *Test*
+
Opens a connection attempt to the host name or IP address.

* *Close*
+
Cancels changes, if any, and closes the dialog box.

*Related information*

xref:reference_credentials_window.adoc[Credentials window]
