---
permalink: help/reference_edit_credentials_dialog_box.html
sidebar: sidebar
keywords: 
summary: 'The Edit Credentials dialog box enables you to modify an existing credential.'
---
= Edit Credentials dialog box
:icons: font
:imagesdir: ../media/

The Edit Credentials dialog box enables you to modify an existing credential.

== Credential parameters

* *Match*
+
Enables you to select the match type of the credential, which defines the credential for either a specific IP address or host name, or an entire subnet or IP range. Available options include the following:

 ** Exact: defines a specific IP address or host name
 ** Pattern: defines an entire subnet or IP range

* *Type*
+
Enables you to select the type of credential from the drop-down list.
+
VMware vCenter is not supported for Linux.

* *Name/IP*
+
Enables you to specify the host name or IP address for the credential.

* *User Name*
+
Enables you to specify the user name for the credential.

* *Password*
+
Enables you to specify the password for the user name.

* *Overwrite Default Values*
+
Enables you to overwrite the default values of the protocol, port, and timeout that are associated with the selected remote system type for the credential.
+
By default, this check box is not selected. You must select the check box if you want to overwrite the default values.

== Protocol table

The protocol table displays the port numbers and timeout limits (in seconds) for protocols associated with the selected remote system for the credential.

== Command buttons

* *Test*
+
Enables you to test the connection to the host name or IP address by logging in using the required credentials.

* *Save*
+
Saves the configuration settings and closes the dialog box.

* *Cancel*
+
Cancels the changes, if any, and closes the dialog box.
