---
permalink: help/reference_clone_command_definition_dialog_box.html
sidebar: sidebar
keywords: clone command definition, dialog box
summary: "The Clone Command Definition dialog box enables you to copy a command and edit the cloned command."
---
= Clone Command Definition dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Clone Command Definition dialog box enables you to copy a command and edit the cloned command.

* Properties tab
* Code tab
* Parameters Definition tab
* Parameters Mapping tab
* Reservation tab
* Verification tab

== Properties tab

Enables you to edit the properties of the cloned command, such as the name, description, and entity version.

* *Name*
+
Enables you to edit the name of the cloned command. By default, the name of the command that you have selected to clone is used as the name for the clone, appended with "`- copy`".

* *Entity Version*
+
Enables you to edit the version number of the command in major.minor.revision format--for example, 1.0.0.

* *Description*
+
Enables you to edit the description of the command.

* *String Representation*
+
Enables you to specify a string representation for the command using MVFLEX Expression Language (MVEL) syntax. You must specify the string representation in order to save the command.

* *Timeout (s)*
+
Enables you to specify the timeout value (in seconds) for the command. The default value is 600 seconds.

* *Command Type*
+
Enables you to specify the type of execution for the command.

 ** *Standard execution*
+
Enables the command to be executed without any waiting period. Standard execution is selected by default.

 ** *Wait for condition*
+
Enables you to specify the time (in seconds) for which the command has to wait before execution. The default value is 60 seconds.

* *Minimum Software Versions*
+
Specifies the minimum versions of the software that are required for the command to operate. For example, the software can be clustered Data ONTAP 8.2.0 and vCenter 6.0. The versions are displayed as comma-separated values.

* *Retain reservation and verification scripts from original command*
+
Enables you to retain the reservation and verification scripts that were originally specified for the command that you want to clone.

== Code tab

Enables you to edit the code for the command.

* *Discover Parameters*
+
Copies the parameters defined in the PowerShell code to the Parameters Definition table and the Parameters Mapping table.

== Parameters Definition tab

Displays the parameters defined in the code that you entered in the Code tab.

* *Name*
+
Displays the name of the parameter.

* *Description*
+
Displays the description of the parameter.

* *Mandatory*
+
Displays a selected check box for the mandatory parameters.

* *Type*
+
Displays the type of the parameter, such as string or enum.

* *Values*
+
Displays the values that are set for the parameter.

* *Add Parameter*
+
Enables you to add a parameter to the command if the selected scripting language is Perl.

* *Remove Parameter*
+
Enables you to remove a parameter from the command if the selected scripting language is Perl.

== Parameters Mapping tab

Enables you to map the parameters to dictionary objects and to specify the attribute and object name.

* *Name*
+
Displays the name of the parameter.

* *Type*
+
Enables you to select a dictionary object for the parameter.

* *Attribute*
+
Enables you to specify the required attribute. You can either select the attribute (if available), or enter the name of the attribute.

* *Object Name*
+
Enables you to specify a name for the dictionary object.

== Reservation tab

Enables you to reserve the resources that are required by the command.

* *Reservation Script*
+
Enables you to enter an SQL query to reserve the resources that are required by the command. This helps ensure that the required resources are available during a scheduled workflow execution.

* *Reservation Representation*
+
Enables you to specify a string representation for the reservation using MVEL syntax. The string representation is used to display the details of the reservation in the Reservations window.

== Verification tab

Enables you to verify a reservation and remove the reservation after the command is executed.

* *Verification Script*
+
Enables you to enter an SQL query to verify the usage of the resources that were reserved by the reservation script. The verification script also verifies whether the WFA cache is updated, and removes the reservation after a cache acquisition.

* *Test Verification*
+
Opens the Verification dialog box, which enables you to test the parameters of the verification script.

== Command buttons

* *Test*
+
Opens the Testing Command <CommandName> in <ScriptLanguage> dialog box, which enables you to test the command.

* *Save*
+
Saves the command and closes the dialog box.

* *Cancel*
+
Cancels changes, if any, and closes the dialog box.
