---
permalink: help/reference-edit-data-source-dialog-box.html
sidebar: sidebar
keywords: edit data source dialog box
summary: "The Edit Data Source dialog box enables you to modify an existing data source."
---
= Edit Data Source dialog box
:icons: font
:imagesdir: ../media/

[.lead]
The Edit Data Source dialog box enables you to modify an existing data source.

== Data Source Configuration properties

* *Name*
+
Enables you to modify the name of the data source.

* *Data source type*
+
Displays the data source type for the data source. You cannot modify this field.

* *Host name*
+
Enables you to specify the host name or IP address (IPv4 or IPv6) for the data source.
+
NOTE: The OnCommand Unified Manager data source type does not support IPv6 addresses.

* *Port*
+
Displays the associated port number, if any, for the selected data source type. You can change the default port number for the data source.

* *Scheme*
+
Displays the scheme associated with the selected data source type--for example _cm_storage_ for Unified Manager - 6.0 (MYSQL).
+
You cannot modify this property.

* *User name*
+
Displays the associated user name, if any, for the selected data source type.
+
You must specify the appropriate user name for this data source to override the default user name:

 ** For Unified Manager versions earlier than 6.0, you must enter the user name that you used for overriding the default credentials while running ocsetup.
 ** For Unified Manager 6.0 and later, you must enter the user name of the database user account that you created on the Unified Manager server.
 ** For Performance Advisor, you must enter the user name of an OnCommand Unified Manager user with a minimum role of GlobalRead.

* *Password*
+
Enables you to specify a password for the selected data source type.
+
You must specify a password to override the default password for the user name of this data source:

 ** For Unified Manager versions earlier than 6.0, you must enter the password that you used for overriding the default credentials while running ocsetup.
 ** For Unified Manager 6.0 and later, you must enter the password of the database user account that you created on the server.
 ** For Performance Advisor, you must enter the password of an Unified Manager user with a minimum role of GlobalRead.

* *Database*
+
Displays the associated database name, if any, for the selected data source type.

* *Interval (minutes)*
+
Enables you to click the value and select an interval (in minutes) using the up and down arrows.
+
NOTE: If the interval is set to zero (0), automatic sampling is disabled.
+
The default interval for data sampling is:

 ** Script based data source type: 1440 (performance and vc)
 ** SQL based data source type: 30 (cm_storage, storage, and cm_performance)

* *See Setup Instruction Guide*
+
Opens the Setup Instruction Guide dialog box, which outlines the steps for setting up the data source.

== Command buttons

* *Reset Scheme*
+
Opens the Reset Scheme confirmation dialog box. This dialog box enables you to reset the cache storage for the selected scheme, which occurs during the next data acquisition.
+
IMPORTANT: The reset process deletes all the cached data, including all the tables. The entire cache is built from start during the next data acquisition.

* *Save*
+
Saves the configurations settings and closes the dialog box.

* *Cancel*
+
Cancels changes, if any, and closes the dialog box.
