---
permalink: workflows/concept_how_you_use_templates.html
sidebar: sidebar
keywords: 
summary: 'You can use WFA templates in your workflows as a reference or for adhering to usage policies.'
---
= How you use templates
:icons: font
:imagesdir: ../media/

You can use WFA templates in your workflows as a reference or for adhering to usage policies.

A WFA template acts as a blueprint of an object definition. You can define a template by including the properties of an object and the values for the object's properties. Then, you can use the template for populating the properties of an object definition in your workflows.

When you use a template, you cannot edit the fields that include the values that are obtained from the template. Therefore, you can use templates for setting up usage policies and creation of objects. If you remove the association of a template with the workflow after you have applied the template, the values populated from the template remain, but you can edit the fields.

*Related information*

xref:task_creating_a_template.adoc[Creating a template]
