---
permalink: workflows/reference_guidelines_for_adding_custom_powershell_modules_to_wfa.html
sidebar: sidebar
keywords: considerations, add, custom, powershell, Perl modules
summary: "You must be aware of certain considerations before adding custom PowerShell and Perl modules to OnCommand Workflow Automation (WFA). Custom PowerShell and Perl modules enable you to use custom commands for creating workflows."
---
= Considerations for adding custom PowerShell and Perl modules
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of certain considerations before adding custom PowerShell and Perl modules to OnCommand Workflow Automation (WFA). Custom PowerShell and Perl modules enable you to use custom commands for creating workflows.

* During the execution of WFA commands, all custom PowerShell modules are added to the WFA install directory _/Posh/modules_ are automatically imported.
* All custom Perl modules added to the _WFA/perl_ directory are included in the _@INC_ library.
* Custom PowerShell and Perl modules are not backed up as part of the WFA backup operation.
* Custom PowerShell and Perl modules are not restored as part of the WFA restore operation.

You must manually back up custom PowerShell and Perl modules in order to copy them to a new WFA installation.

The folder name in modules' directory must be same as that of the module name.
