---
permalink: workflows/reference_guidelines_for_data_source_type.html
sidebar: sidebar
keywords: guidelines, create, data, source, types
summary: "You must be aware of the guidelines for creating data source types that are used to define custom data sources for OnCommand Workflow Automation (WFA)."
---
= Guidelines for creating data source types
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of the guidelines for creating data source types that are used to define custom data sources for OnCommand Workflow Automation (WFA).

You can define a data source type by using one of the following methods:

* SQL: You can use the WFA SQL guidelines to define select queries from data sources based on an external database.
* SCRIPT: You can write a PowerShell script that provides the data for a specific scheme of dictionary entries.

The guidelines for creating data source types are as follows:

* You should use PowerShell language must be used to create script.
* The PowerShell script should provide the output for each dictionary entry in its current working directory.
* The data files should be named `dictionary_entry.csv`, where the name of the dictionary entry should be in lower-case characters.
+
The predefined data source type that collects information from Performance Advisor uses a SCRIPT-based data source type. The output files are named `array_performance.csv` and `aggregate_performance.csv`.

* The .csv file should include the content in the exact order as that of the dictionary entry attributes.
+
A dictionary entry includes attributes in the following order: array_ip, date, day, hour, cpu_busy, total_ops_per_sec, disk_throughput_per_sec.
+
The PowerShell script adds data to the `.csv` file in the same order.
+
----
$values = get-Array-CounterValueString ([REF]$data)
Add-Content $arrayFile ([byte[]][char[]] "\N t$arrayIP't$date't$day't$hour't$values'n")
----

* You should use Encoding to ensure that the data output from the script is loaded into the WFA cache accurately.
* You should use \N while entering a Null value in the `.csv` file.
