---
permalink: workflows/task_testing_the_wfa_reservation_script_for_commands.html
sidebar: sidebar
keywords: 
summary: 'You can test the reservation scripts you have written for OnCommand Workflow Automation \(WFA\) commands on the playground database to ensure that the scripts are working fine and not affecting the WFA database tables.'
---
= Testing the reservation script for commands
:icons: font
:imagesdir: ../media/

[.lead]
You can test the reservation scripts you have written for OnCommand Workflow Automation (WFA) commands on the playground database to ensure that the scripts are working fine and not affecting the WFA database tables.

The default WFA installation path is used in this procedure. If you changed the default location during installation, you must use the changed WFA installation path.

. Open a command prompt on the WFA server and change directories to the following location: c:\Program Files\NetApp\WFA\mysql\bin
. Create a dump of the WFA database using the following command: `mysqldump -u wfa -pWfa123 --single-transaction --skip-add-drop-table database_tables> dump_location`
+
Command to create a dump of the cm_storage database tables: `mysqldump -u wfa -pWfa123 --single-transaction --skip-add-drop-table cm_storage> c:\tmp\cmSt2.sql`

. Restore the dump you have created on to the WFA playground database using the following command: `mysql -u wfa -pWfa123 playground < dump_location`
+
`mysql -u wfa -pWfa123 playground < c:\tmp\cmSt2.sql`

. Create or edit a WFA command and write the reservation script in the *Reservation* tab.
+
You must ensure that the reservation and verification scripts use only the playground database.

. Create or edit a workflow, include the command in the workflow, and then execute the workflow.
. Verify that the reservation and verification scripts are working as expected.
+
The WFA data source acquisition process does not update the playground database. You must remove the reservations created by the command manually.
