---
permalink: workflows/task_add_entity_to_a_workflow_automation_pack.html
sidebar: sidebar
keywords: oncommand workflow automation, add, entities, wfa, workflow, packs
summary: "You can add one or more entities to a workflow pack in OnCommand Workflow Automation (WFA) for your storage automation and integration requirements."
---
= Add entities to WFA workflow packs
:icons: font
:imagesdir: ../media/

[.lead]
You can add one or more entities to a workflow pack in OnCommand Workflow Automation (WFA) for your storage automation and integration requirements.

*About this task*

You can remove a pack from the following entities:

* Workflow
* Finders
* Filters
* Commands
* Functions
* Templates
* Schemes
* Dictionary
* Data Sources Types
* Remote System Types
* Cache Queries
* Categories

.Steps
. Log in to the *WFA* window through a web browser.
. Click *Designer* > *<Entities>*.
. In the Entity window, select the entity you want to add to the pack.
. Click the *Add To Pack* icon.
+
"`Add To Pack`" is enabled only for entities for which the certification is set to `None`.

. In the *Add To Pack <Entity>* dialog box, from the *Available Packs* drop-down list, select the pack to which you want to add the entity.
. Click *OK*.
